#include "web_ui_page.h"

static const char s_web_ui_index[] =
"<!DOCTYPE html><html><head><meta charset='utf-8'><title>Broker</title>"
        "<style>"
        "body{margin:0;padding:0;font-family:Arial,sans-serif;background:#0b0d12;color:#e6e7ea;display:flex;justify-content:center;}"
        ".page{width:100%;max-width:1400px;margin:0 auto;}"
        "header{padding:18px 24px;border-bottom:1px solid #181c26;background:#0f1219;position:sticky;top:0;display:flex;justify-content:center;z-index:40;}"
        ".tabs{display:flex;flex-wrap:wrap;--tab-gap:10px;gap:var(--tab-gap);padding:10px 12px;background:#0f1219;border:1px solid #181c26;border-radius:12px;margin:0 auto 12px;width:100%;max-width:1200px;justify-content:center;}"
        ".tab{height:42px;flex:0 0 calc((100% - 7*var(--tab-gap))/8);max-width:calc((100% - 7*var(--tab-gap))/8);min-width:100px;padding:0 12px;border-radius:12px;cursor:pointer;border:2px solid var(--tab-color,#121621);background:var(--tab-color,#121621);color:#f8fafc;font-weight:600;display:inline-flex;align-items:center;justify-content:center;gap:8px;font-size:13px;box-shadow:0 6px 18px rgba(0,0,0,0.3);transition:transform .15s ease,box-shadow .2s ease,opacity .2s ease;}"
        ".tab:not(.active){opacity:0.88;}"
        ".tab.active{transform:translateY(-1px);box-shadow:0 10px 26px rgba(0,0,0,0.45),0 0 0 2px rgba(255,255,255,0.2);}"
        ".tab .tab-icon{width:20px;height:20px;border-radius:8px;background:rgba(11,13,19,0.15);display:inline-flex;align-items:center;justify-content:center;background-repeat:no-repeat;background-position:center;background-size:16px;color:#0b0d13;flex-shrink:0;}"
        ".tab .tab-label{white-space:nowrap;}"
        ".tab[data-icon='status'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25230b0d13%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Cpolyline%20points%3D%273%2012%207%2012%2010%206%2014%2018%2017%2012%2021%2012%27%2F%3E%3C%2Fsvg%3E\");}"
        ".tab[data-icon='audio'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25230b0d13%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Cpolygon%20points%3D%275%209%209%209%2013%205%2013%2019%209%2015%205%2015%205%209%27%2F%3E%3Cpath%20d%3D%27M16%209c1.5%201.5%201.5%204.5%200%206%27%2F%3E%3Cpath%20d%3D%27M19%207c2.5%202.5%202.5%207.5%200%2010%27%2F%3E%3C%2Fsvg%3E\");}"
        ".tab[data-icon='settings'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25230b0d13%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Ccircle%20cx%3D%2712%27%20cy%3D%2712%27%20r%3D%273%27%2F%3E%3Cpath%20d%3D%27M19.4%2015a1.65%201.65%200%200%200%20.33%201.82l.06.06a2%202%200%200%201-2.83%202.83l-.06-.06a1.65%201.65%200%200%200-1.82-.33%201.65%201.65%200%200%200-1%201.51V21a2%202%200%200%201-4%200v-.09A1.65%201.65%200%200%200%209%2019.4a1.65%201.65%200%200%200-1.82.33l-.06.06a2%202%200%200%201-2.83-2.83l.06-.06a1.65%201.65%200%200%200%20.33-1.82%201.65%201.65%200%200%200-1.51-1H3a2%202%200%200%201%200-4h.09A1.65%201.65%200%200%200%204.6%209%201.65%201.65%200%200%200%204.27%207.18l-.06-.06A2%202%200%200%201%207.04%204.3l.06.06A1.65%201.65%200%200%200%208.91%204a1.65%201.65%200%200%200%201-1.51V3a2%202%200%200%201%204%200v.09A1.65%201.65%200%200%200%2015%204.6a1.65%201.65%200%200%200%201.82-.33l.06-.06a2%202%200%200%201%202.83%202.83l-.06.06A1.65%201.65%200%200%200%2019.74%209%201.65%201.65%200%200%200%2021.25%2010H21a2%202%200%200%201%200%204h-.09a1.65%201.65%200%200%200-1.51%201z%27%2F%3E%3C%2Fsvg%3E\");}"
        ".tab[data-icon='devices'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25230b0d13%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Cpath%20d%3D%27M12%201V7%27/%3E%3Crect%20x%3D%275%27%20y%3D%279%27%20width%3D%2714%27%20height%3D%2711%27%20rx%3D%272%27/%3E%3Cpath%20d%3D%27M8%2020v3h8v-3%27/%3E%3Cpath%20d%3D%27M8%2013h8%27/%3E%3Ccircle%20cx%3D%2212%22%20cy%3D%2216%22%20r%3D%221%22/%3E%3C/svg%3E\");}"
".tab[data-icon='network'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25230b0d13%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Cpath%20d%3D%27M5%2012a9%209%200%200%201%2014%200%27%2F%3E%3Cpath%20d%3D%27M8.5%2015.5a5%205%200%200%201%207%200%27%2F%3E%3Cpath%20d%3D%27M12%2019h.01%27%2F%3E%3C%2Fsvg%3E\");}"
".tab[data-icon='power'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25230b0d13%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Cline%20x1%3D%2712%27%20y1%3D%272%27%20x2%3D%2712%27%20y2%3D%2712%27%2F%3E%3Cpath%20d%3D%27M5.5%207.5a7%207%200%201%200%2013%200%27%2F%3E%3C%2Fsvg%3E\");}"
".tab[data-icon='monitor'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' stroke='%230b0d13' stroke-width='2' fill='none' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='M3 3h18v14H3z'/%3E%3Cpath d='M3 13l4-4 3 3 4-5 4 4'/%3E%3Cpath d='M8 21h8'/%3E%3Cpath d='M12 17v4'/%3E%3C/svg%3E\");}"
".pane{padding:24px;display:none;max-width:1200px;margin:0 auto;} .pane.active{display:block;}"
".card{background:#121621;border:1px solid #1f2430;border-radius:12px;padding:16px;margin:0 auto 14px;box-shadow:0 10px 30px rgba(0,0,0,0.25);}"
".dx-editor-pane{display:none;}"
".dx-editor-pane.active{display:block;}"
"h3,h4{margin:0 0 10px;color:#f0f2f5;font-weight:600;}"
        "input,select{background:#0c0e12;border:1px solid #2b3344;color:#e6e7ea;border-radius:8px;padding:10px 12px;margin:4px 8px 4px 0;min-width:220px;}"
        "button:not(.icon-btn){background:#3b82f6;border:none;color:#fff;border-radius:10px;padding:10px 16px;margin:4px 8px 4px 0;cursor:pointer;font-weight:600;box-shadow:0 6px 18px rgba(59,130,246,0.35);}button:not(.icon-btn):hover{background:#2563eb;}"
        ".muted{color:#8b92a3;font-size:13px;}"
        ".row{display:flex;flex-wrap:wrap;align-items:center;}"
        ".mqtt-user-row{display:flex;flex-wrap:wrap;align-items:center;gap:8px;margin:6px 0;}"
        ".mqtt-user-row input{flex:1 1 140px;min-width:150px;}"
        ".mqtt-user-row button{flex:0 0 auto;}"
        ".controls-row{display:flex;align-items:center;gap:16px;flex-wrap:wrap;}"
        ".volume-control{display:flex;align-items:center;gap:10px;min-width:200px;flex:1 1 200px;}"
        ".volume-control input{max-width:220px;}"
        ".control-buttons{display:flex;gap:10px;flex-shrink:0;}"
        ".mode-row{gap:10px;}"
        ".mode-btn{min-width:120px;font-weight:600;border:2px solid #1f2430;background:#0c0e12;color:#cbd5e1;border-radius:10px;padding:10px 14px;cursor:pointer;transition:box-shadow .2s ease,border-color .2s ease,color .2s ease,background .2s ease;}"
        ".mode-btn.active{border-color:#3b82f6;background:#0f172a;color:#fff;box-shadow:0 0 12px rgba(59,130,246,0.35);}"
        ".mode-btn.mode-last{box-shadow:0 0 0 2px rgba(59,130,246,0.6),0 0 16px rgba(59,130,246,0.35);}"
        ".progress-box{border:1px solid rgba(59,130,246,0.4);border-radius:14px;background:linear-gradient(140deg,#0b1120,#131c31);padding:12px 16px;margin-top:10px;display:flex;flex-direction:column;gap:6px;box-shadow:0 12px 28px rgba(2,6,23,0.65);color:#e2e8f0;backdrop-filter:blur(8px);}"
        ".progress-row{display:flex;flex-direction:column;align-items:stretch;gap:2px;}"
        ".progress-row input{flex:0 0 auto;min-width:220px;width:100%;}"
        ".progress-row .muted{font-size:12px;}"
        "input[type=range]{-webkit-appearance:none;appearance:none;padding:0;background:transparent;border:none;min-width:0;height:26px;display:block;margin:4px 0;}"
        "input[type=range]:focus{outline:none;}"
        "input[type=range]::-webkit-slider-runnable-track{width:100%;height:6px;background:#1f2430;border-radius:999px;border:1px solid #2b3344;}"
        "input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;appearance:none;width:16px;height:16px;border-radius:50%;background:#3b82f6;border:2px solid #0b0d13;margin-top:-6px;box-shadow:0 0 0 2px rgba(59,130,246,0.3);cursor:pointer;}"
        "input[type=range]::-moz-range-track{width:100%;height:6px;background:#1f2430;border-radius:999px;border:1px solid #2b3344;}"
        "input[type=range]::-moz-range-thumb{width:16px;height:16px;border-radius:50%;background:#3b82f6;border:2px solid #0b0d13;cursor:pointer;}"
        "input[type=range]::-ms-track{width:100%;height:6px;background:transparent;border-color:transparent;color:transparent;}"
        "input[type=range]::-ms-fill-lower{background:#1f2430;border-radius:999px;border:1px solid #2b3344;}"
        "input[type=range]::-ms-fill-upper{background:#1f2430;border-radius:999px;border:1px solid #2b3344;}"
        "input[type=range]::-ms-thumb{width:16px;height:16px;border-radius:50%;background:#3b82f6;border:2px solid #0b0d13;cursor:pointer;margin-top:0;}"
        ".list{margin:6px 0;}"
        ".pill{display:inline-block;padding:6px 10px;border-radius:12px;background:#1f2430;margin:4px;color:#cbd5e1;font-size:13px;cursor:pointer;}"
        ".badge{display:inline-block;padding:6px 10px;border-radius:12px;background:#1f2430;margin-left:8px;font-size:12px;}"
        ".hero{padding:16px 24px;background:#0f1219;border:1px solid #181c26;border-radius:12px;margin:0 auto 12px;max-width:1200px;display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap;}"
        ".hero h2{margin:0;font-weight:700;color:#f0f2f5;}"
        ".hero .status-clusters{display:flex;gap:16px;align-items:center;flex-wrap:wrap;margin-left:auto;}"
        ".device-cluster{display:flex;align-items:center;gap:6px;background:#0c0e12;border:1px solid #1f2430;padding:6px 10px;border-radius:10px;min-width:110px;justify-content:center;}"
        ".device-cluster .label{font-size:12px;color:#8b92a3;display:flex;align-items:center;gap:4px;}"
        ".device-cluster .dots{display:flex;gap:4px;}"
        ".device-cluster .dots span{width:10px;height:10px;border-radius:50%;background:#1f2937;}"
        ".device-icon{font-size:16px;}"
        ".stat-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:10px;margin-top:12px;}"
        ".stat{background:#0c0e12;border:1px solid #1f2430;border-radius:10px;padding:10px 12px;}"
        ".stat .label{display:block;color:#8b92a3;font-size:12px;margin-bottom:4px;}"
        ".stat .value{font-weight:600;color:#e6e7ea;}"
        ".dots span{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:4px;background:#1f2937;}"
".small{font-size:12px;}"
".status-row{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin:6px 0;}"
".uid-monitor{display:flex;flex-direction:column;gap:12px;}"
".uid-device{border:1px solid #1f2430;border-radius:10px;padding:10px;background:#0c0e12;}"
".uid-device h4{margin:0 0 6px;font-size:15px;color:#f1f5f9;}"
".uid-slots{display:flex;flex-wrap:wrap;gap:8px;}"
".uid-slot{min-width:140px;border:1px dashed #1f2430;border-radius:8px;padding:6px 8px;background:#05070b;color:#e5e7eb;font-size:12px;}"
".uid-slot .label{display:block;color:#94a3b8;font-size:11px;margin-bottom:2px;}"
".sensor-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px;margin-top:12px;}"
".sensor-card{background:#0c0e12;border:1px solid #1f2430;border-radius:12px;padding:14px;display:flex;flex-direction:column;gap:10px;min-height:160px;box-shadow:0 10px 30px rgba(0,0,0,0.25);}"
".sensor-card.status-ok{border-color:#1f2430;}"
".sensor-card.status-warn{border-color:#facc15;background:rgba(250,204,21,0.08);}"
".sensor-card.status-alarm{border-color:#f87171;background:rgba(248,113,113,0.1);}"
".sensor-card.status-unknown{border-style:dashed;}"
".sensor-header{display:flex;justify-content:space-between;gap:10px;align-items:flex-start;}"
".sensor-name{font-weight:600;color:#f8fafc;}"
".sensor-topic{font-size:11px;color:#94a3b8;word-break:break-all;}"
".sensor-status-pill{border-radius:999px;padding:4px 10px;font-size:11px;font-weight:600;text-transform:uppercase;}"
".sensor-status-pill.status-ok{background:#14532d;color:#bbf7d0;}"
".sensor-status-pill.status-warn{background:#78350f;color:#fde68a;}"
".sensor-status-pill.status-alarm{background:#7f1d1d;color:#fecaca;}"
".sensor-status-pill.status-unknown{background:#1f2937;color:#e2e8f0;}"
".sensor-value{font-size:28px;font-weight:700;color:#f8fafc;display:flex;align-items:flex-end;gap:8px;}"
".sensor-value .sensor-units{font-size:16px;color:#94a3b8;font-weight:500;}"
".sensor-meta{font-size:12px;color:#94a3b8;display:flex;gap:12px;flex-wrap:wrap;}"
".sensor-thresholds{font-size:12px;color:#cbd5e1;display:flex;flex-direction:column;gap:2px;}"
".sensor-thresholds-line{display:flex;justify-content:space-between;gap:6px;flex-wrap:wrap;}"
".sensor-thresholds .label{font-weight:600;margin-right:4px;color:#94a3b8;}"
".sensor-history{display:flex;flex-wrap:wrap;gap:4px;margin-top:6px;}"
".sensor-history .history-chip{padding:3px 8px;border-radius:999px;font-size:11px;background:#1f2430;color:#e2e8f0;}"
".sensor-history .history-chip.status-warn{background:#78350f;color:#fde68a;}"
".sensor-history .history-chip.status-alarm{background:#7f1d1d;color:#fecaca;}"
".sensor-empty{font-size:13px;color:#94a3b8;margin-top:8px;}"
".file-browser{margin-top:12px;border:1px solid rgba(59,130,246,0.35);background:linear-gradient(140deg,#050a16,#0f172a);border-radius:18px;padding:18px;max-width:1200px;margin-left:auto;margin-right:auto;box-shadow:0 22px 60px rgba(2,6,23,0.65);backdrop-filter:blur(10px);}"
        ".folder-row{display:flex;flex-wrap:wrap;gap:10px;margin:10px auto;width:100%;max-width:calc(8*100px + 7*10px);justify-content:center;min-height:50px;align-items:center;}"
        ".folder-chip{width:100px;height:56px;border:2px solid rgba(248,250,252,0.2);border-radius:14px;background:linear-gradient(160deg,rgba(15,23,42,0.95),rgba(2,6,23,0.9));cursor:pointer;font-size:12px;color:#f8fafc;display:flex;align-items:center;justify-content:center;box-sizing:border-box;overflow:hidden;text-align:center;font-weight:600;letter-spacing:0.04em;text-transform:uppercase;box-shadow:0 12px 28px rgba(2,6,23,0.65);}"
        ".folder-chip:hover{border-color:rgba(248,250,252,0.8);box-shadow:0 14px 34px rgba(248,250,252,0.35);}"
        ".folder-chip.active{box-shadow:0 0 0 2px rgba(248,250,252,0.6),0 18px 40px rgba(248,250,252,0.4);background:linear-gradient(140deg,#0f172a,#2563eb);}"
        ".file-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(100px,1fr));grid-auto-rows:100px;gap:10px;margin:8px auto 0;width:100%;max-width:calc(8*100px + 7*10px);justify-content:center;}"
        ".track-card{border-radius:12px;width:100px;height:100px;display:flex;align-items:flex-end;justify-content:center;position:relative;overflow:hidden;color:#0b0d13;border:3px solid var(--pad-border,rgba(255,255,255,0.18));background:radial-gradient(circle at 50% 38%,rgba(255,255,255,0.9) 0%,rgba(255,255,255,0.7) 18%,var(--pad-color,#6b7280) 55%,#05070b 100%);cursor:pointer;box-shadow:0 12px 30px rgba(0,0,0,0.55),0 0 22px var(--pad-glow,rgba(0,0,0,0.35));z-index:1;transition:transform .15s ease,box-shadow .2s ease,border-color .2s ease;}"
        ".track-card::after{content:'';position:absolute;inset:8px;border-radius:10px;background:radial-gradient(circle,rgba(255,255,255,0.35) 0%,transparent 65%);pointer-events:none;opacity:.9;}"
        ".track-card.playing{box-shadow:0 0 35px var(--pad-border,rgba(248,250,252,0.9)),0 0 80px var(--pad-glow,rgba(248,250,252,0.6)),inset 0 0 35px rgba(255,255,255,0.55);border-color:var(--pad-border,#f8fafc);z-index:3;transform:translateY(-4px) scale(1.02);}"
        ".track-name{position:relative;z-index:1;width:100%;text-align:center;padding:8px 4px;box-sizing:border-box;color:#0b0d13;font-weight:700;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px;text-shadow:0 1px 3px rgba(255,255,255,0.4);background:rgba(255,255,255,0.18);text-transform:uppercase;letter-spacing:0.05em;}"
        ".icon-btn{width:36px;height:36px;border:1px solid rgba(59,130,246,0.4);border-radius:10px;background:linear-gradient(140deg,#0f172a,#1e293b);color:#f1f5f9;display:inline-flex;align-items:center;justify-content:center;cursor:pointer;margin-left:12px;position:relative;box-shadow:0 12px 26px rgba(2,6,23,0.65);}"
        ".icon-btn::before{content:'';display:block;width:14px;height:14px;}"
        ".icon-btn:hover{border-color:#38bdf8;color:#e0f2fe;box-shadow:0 14px 30px rgba(56,189,248,0.5);}"
        ".icon-btn.active{border-color:#38bdf8;box-shadow:0 0 0 2px rgba(56,189,248,0.5),0 16px 32px rgba(14,165,233,0.5);background:linear-gradient(140deg,#0f172a,#2563eb);color:#f8fafc;}"
        ".icon-btn.icon-stop::before{width:12px;height:12px;background:#f87171;border-radius:3px;}"
        ".icon-btn.icon-pause::before{background:linear-gradient(90deg,#cbd5e1 0,#cbd5e1 40%,transparent 40%,transparent 60%,#cbd5e1 60%,#cbd5e1 100%);}"
        ".icon-btn.icon-play::before{content:'';width:0;height:0;border-left:12px solid #cbd5e1;border-top:6px solid transparent;border-bottom:6px solid transparent;margin-left:2px;}"
        ".icon-btn.icon-repeat::before{background-image:url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' stroke='%23cbd5e1' stroke-width='2' fill='none' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpolyline points='17 1 21 5 17 9'/%3E%3Cpath d='M3 11V9a4 4 0 0 1 4-4h14'/%3E%3Cpolyline points='7 23 3 19 7 15'/%3E%3Cpath d='M21 13v2a4 4 0 0 1-4 4H3'/%3E%3C/svg%3E\");background-size:contain;background-repeat:no-repeat;}"
        "table{width:100%;border-collapse:collapse;margin-top:10px;}"
        "td,th{border:1px solid #1f2430;padding:8px;}"
        "@media(max-width:600px){header{padding:12px;} .pane{padding:16px;width:100%;} .card{margin:0 0 12px;width:100%;} .hero{margin:0 0 12px;padding:12px;} .row{flex-direction:column;align-items:stretch;} .row button,.row select,.row input{width:100%;max-width:100%;} .controls-row{flex-direction:column;align-items:stretch;} .control-buttons{justify-content:space-between;} .volume-control{width:100%;} .progress-row input{max-width:100%;} .file-browser{padding:10px;} .file-grid{grid-template-columns:repeat(4,minmax(0,1fr));max-width:none;}}"
"</style><link rel='stylesheet' href='/ui/devices.css?v=3'></head><body>"
        "<div class='page'>"
        "<header><div class='tabs'>"
        "<div class='tab active' data-tab='status' data-icon='status'><span class='tab-icon'></span><span class='tab-label'>Status</span></div>"
        "<div class='tab' data-tab='audio' data-icon='audio'><span class='tab-icon'></span><span class='tab-label'>Audio</span></div>"



"<div class='tab' data-tab='devices' data-icon='devices'><span class='tab-icon'></span><span class='tab-label'>Devices</span></div>"
"<div class='tab' data-tab='actions' data-icon='power'><span class='tab-icon'></span><span class='tab-label'>Actions</span></div>"
"<div class='tab' data-tab='monitor' data-icon='monitor'><span class='tab-icon'></span><span class='tab-label'>Monitoring</span></div>"
"<div class='tab' data-tab='settings' data-icon='settings'><span class='tab-icon'></span><span class='tab-label'>Settings</span></div>"
"</div></header>"
        "<div class='hero'><h2>Broker</h2><div id='banner' class='muted'>Loading status...</div></div>"
        "<div class='pane active' id='pane-status'>"
"<div class='card'><h3>Status<span id='status_badge' class='badge'></span></h3>"
        "<div class='status-row'><button onclick='ping()'>Ping</button><button onclick='loadStatus()'>Refresh</button><button id='status_raw_btn' onclick='toggleRaw()'>Show raw</button><span id='status_state' class='muted'>Loading...</span></div>"
        "<div class='stat-grid'>"
"<div class='stat'><span class='label'>Wi-Fi SSID</span><span id='status_ssid' class='value'>n/a</span></div>"
"<div class='stat'><span class='label'>STA IP</span><span id='status_ip' class='value'>n/a</span></div>"
"<div class='stat'><span class='label'>SD Size</span><span id='status_sd_size' class='value'>n/a</span></div>"
"<div class='stat'><span class='label'>Clients total</span><span id='status_clients' class='value'>0</span></div>"
"<div class='stat'><span class='label'>RAM free</span><span id='status_ram' class='value'>n/a</span></div>"
"<div class='stat'><span class='label'>PSRAM free</span><span id='status_psram' class='value'>n/a</span></div>"
"</div>"
"<pre id='status_raw' class='muted small' style='display:none;'></pre>"
"</div>"
"<div class='card' id='uid_card' style='display:none;'><h3>UID Monitor</h3><div id='uid_monitor_list' class='uid-monitor'></div></div>"
"</div>"

"<div class='pane' id='pane-monitor'>"
"<div class='card'><h3>Monitoring</h3><p class='muted'>Live sensor telemetry grouped by device.</p><div id='sensor_empty' class='sensor-empty'>No sensors configured.</div><div id='sensor_cards' class='sensor-grid'></div></div>"
"</div>"

        "<div class='pane' id='pane-audio'>"
        "<div class='card'><h3>Audio</h3>"
        "<input id='audio_path' type='hidden'>"
        "<div class='controls-row'><div class='volume-control'><input id='audio_vol' type='range' min='0' max='100' value='70' oninput=\"volInput(this.value)\"><span class='muted'>Volume: <span id='audio_vol_val'>70</span>%</span></div><div class='control-buttons'><button id='audio_repeat_btn' class='icon-btn icon-repeat' onclick='toggleRepeat()' title='Repeat track'></button><button id='audio_pause_btn' class='icon-btn icon-pause' onclick='togglePause()' title='Pause'></button><button id='audio_stop_btn' class='icon-btn icon-stop' onclick='stopPlay()' title='Stop'></button></div></div>"
        "<div class='progress-box'><div class='row progress-row'><input id='audio_prog' type='range' min='0' max='10000' value='0' step='1' oninput=\"scrubPreview(this.value)\" onchange=\"commitScrub(this.value)\" onmousedown=\"startScrub()\" onmouseup=\"finishScrub()\" ontouchstart=\"startScrub()\" ontouchend=\"finishScrub()\" ontouchcancel=\"finishScrub()\"><span class='muted'>Progress: <span id='audio_prog_txt'>0:00 / ?</span></span></div></div>"
        "<div id='audio_status' class='muted small'>Loading files...</div>"
        "<div class='file-browser'>"
        "<div class='row'><button onclick='navUp()'>Up</button><button onclick='loadFiles()'>Refresh files</button><span id='path_label' class='muted small'>/sdcard</span><span class='muted small'>Click track to select</span></div>"
        "<div id='audio_folders' class='folder-row' style='border:1px solid #1f2430;padding:6px 10px;border-radius:12px;background:#0d1018;margin-top:8px;min-height:50px;'></div>"
"<div id='audio_files' class='file-grid' style='border:1px solid #1f2430;padding:10px;border-radius:12px;background:#0d1018;margin-top:8px;'></div>"
"</div>"
"</div></div>"
"<datalist id='track_lookup'></datalist>"

"<div class='pane' id='pane-settings'>"
        "<div class='card'><h3>Settings</h3>"
        "<div class='row'><input id='ssid' placeholder='SSID'><input id='pass' placeholder='Password'><input id='host' placeholder='Hostname'></div>"
        "<button onclick='saveWifi()'>Save Wi-Fi</button>"
        "<button onclick='scanWifi()'>Scan</button>"
        "<div id='wifi_list' class='list'></div>"
        "<div class='muted'>If AP is up: password 12345678.</div>"
        "</div>"
"<div class='card'><h3>MQTT</h3>"
"<div class='row'><input id='mqtt_id' placeholder='Broker ID'><input id='mqtt_port' placeholder='Port' style='max-width:140px'><input id='mqtt_keep' placeholder='Keepalive s' style='max-width:160px'></div>"
"<button onclick='saveMqtt()'>Save</button>"
"<div class='muted small'>MQTT users (client ID + username/password). Devices must use these credentials.</div>"
"<div id='mqtt_users_list' class='list'></div>"
"<div class='controls-row'><button type='button' onclick='addMqttUser()'>Add user</button><button type='button' onclick='saveMqttUsers()'>Save users</button></div>"
"</div>"
"<div class='card'><h3>Web auth</h3>"
"<div class='muted small'>Administrator</div>"
"<div class='row'><input id='web_user' placeholder='Username'><input id='web_pass_current' type='password' placeholder='Current password'><input id='web_pass_new' type='password' placeholder='New password'></div>"
"<button onclick='saveWebPassword()'>Update admin credentials</button><button onclick='logout()'>Log out</button>"
"<div id='web_auth_status' class='muted small'></div>"
"<div class='muted small' style='margin-top:12px;'>Operator (read-only)</div>"
"<div class='row'><input id='op_user' placeholder='Operator username'><input id='op_pass' type='password' placeholder='Operator password'><label class='muted small'><input type='checkbox' id='op_enabled'> Enable operator login</label></div>"
"<input id='op_admin_current' type='password' placeholder='Admin password to confirm' style='margin-top:8px;'>"
"<button onclick='saveOperatorAccount()'>Save operator account</button>"
"<div id='op_auth_status' class='muted small'></div>"
"</div>"
"<div class='card'><h3>Publish MQTT</h3>"
"<div class='row'><input id='pub_topic' placeholder='topic'><input id='pub_payload' placeholder='payload'></div>"
"<button onclick='publishMsg()'>Send</button>"
"</div>"
"<div class='card'><h3>Diagnostics</h3>"
"<label class='muted small'><input type='checkbox' id='diag_verbose'> Enable verbose template logs</label>"
"<div class='muted small'>Use for troubleshooting UID/Signal templates; turn off for normal play.</div>"
"<button onclick='saveDiagnostics()'>Apply</button>"
"</div>"
"</div>"
"<div class='pane' id='pane-devices'>"
"<div class='card dx-card'><h3>Devices & Automation</h3>"
"<div id='device_wizard_root'></div>"
"</div>"
"</div>"
"<div class='pane' id='pane-actions'>"
"<div class='card dx-card'><h3>Scenario Buttons</h3>"
"<div id='actions_root' class='actions-root'>No scenarios yet.</div>"
"</div>"
"</div>"
"<script>"
        "const MAX_PARALLEL_REQUESTS=2;"
"const __fetchQueue=[];"
"let __fetchActive=0;"
"const __origFetch=window.fetch.bind(window);"
"function __handleFetchResponse(res){if(res.status===401){const next=encodeURIComponent(window.location.pathname||'/');window.location='/login?next='+next;throw new Error('Unauthorized');}return res;}"
"function __runFetchQueue(){if(__fetchActive>=MAX_PARALLEL_REQUESTS)return;const job=__fetchQueue.shift();if(!job)return;__fetchActive++;__origFetch(...job.args).then(__handleFetchResponse).then(job.resolve,job.reject).finally(()=>{__fetchActive--;__runFetchQueue();});}"
"window.fetch=(...args)=>new Promise((resolve,reject)=>{__fetchQueue.push({args,resolve,reject});__runFetchQueue();});"
"window.__WEB_SESSION=null;"
        "const tabs=document.querySelectorAll('.tab');const panes=document.querySelectorAll('.pane');"
"const tabIconDefaults=['status','audio','devices','settings'];"
"tabs.forEach((tab,idx)=>{if(!tab.dataset.icon){tab.dataset.icon=tabIconDefaults[idx%tabIconDefaults.length];}});"
"const loadedTabs={status:true,audio:false};"
        "tabs.forEach(t=>t.onclick=()=>{tabs.forEach(x=>x.classList.remove('active'));panes.forEach(p=>p.classList.remove('active'));t.classList.add('active');document.getElementById('pane-'+t.dataset.tab).classList.add('active');ensureTabLoaded(t.dataset.tab);});"
"function applyRoleLayout(role){const body=document.body;if(body){body.dataset.role=role||'admin';}if(role!=='user'){if(document.body){document.body.classList.remove('role-user');}tabs.forEach(tab=>{tab.style.display='';});return;}document.body.classList.add('role-user');const banner=document.getElementById('banner');if(banner){banner.textContent='Scenario console';}const allowed=new Set(['actions','monitor']);let activeTab=null;tabs.forEach(tab=>{if(allowed.has(tab.dataset.tab)){tab.style.display='';if(!activeTab&&tab.dataset.tab==='actions'){activeTab=tab;}}else{tab.style.display='none';tab.classList.remove('active');}});if(!activeTab){activeTab=document.querySelector(\".tab[data-tab='monitor']\");}tabs.forEach(tab=>{if(tab===activeTab){tab.classList.add('active');}else{tab.classList.remove('active');}});panes.forEach(pane=>{const key=pane.id.replace('pane-','');if(activeTab&&key===activeTab.dataset.tab){pane.classList.add('active');}else if(allowed.has(key)){pane.classList.remove('active');}else{pane.classList.remove('active');}});}"
"function loadSessionRole(){return fetch('/api/session/info').then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(info=>{window.__WEB_SESSION=info||{role:'admin',username:''};applyRoleLayout(window.__WEB_SESSION.role||'admin');return info;}).catch(()=>{window.__WEB_SESSION={role:'admin',username:''};applyRoleLayout('admin');return window.__WEB_SESSION;});}"
"const sessionRolePromise=loadSessionRole();"
"window.__sessionRolePromise=sessionRolePromise;"
"function ensureTabLoaded(tab){switch(tab){case 'audio':if(!loadedTabs.audio){loadFiles().then(()=>{loadedTabs.audio=true;}).catch(()=>{});}break;default:break;}}"
        "function ping(){fetch('/api/ping').then(r=>r.text()).then(alert);} "
        "let apPopupShown=false;"
        "function updateBanner(j){const b=document.getElementById('banner');const badge=document.getElementById('status_badge');const ap=j.wifi.ap;const ip=j.wifi.sta_ip;badge.textContent=ap?'AP+STA':'STA';badge.style.background=ap?'#f97316':'#1f2430';if(ap){b.textContent='Setup mode: AP+STA, will disable AP after connect.';}else{b.textContent='Connected to '+j.wifi.ssid+' IP '+(ip||'none');}}"
"function setTxt(id,v){const el=document.getElementById(id);if(el){el.textContent=v;}}"
"function escapeHtml(text){if(text===undefined||text===null)return'';return String(text).replace(/[&<>\"']/g,c=>({\"&\":\"&amp;\",\"<\":\"&lt;\",\">\":\"&gt;\",\"\\\"\":\"&quot;\",\"'\":\"&#39;\"}[c]||c));}"
        "function renderDots(id,count,max){const el=document.getElementById(id);if(!el)return;el.innerHTML='';for(let i=0;i<max;i++){const dot=document.createElement('span');dot.style.background=i<count?'#22c55e':'#1f2937';el.appendChild(dot);}}"
        "function humanMb(bytes){if(!bytes||bytes<=0)return'-';return (bytes/1024/1024).toFixed(1)+' MB';}"
        "function humanGb(bytes){if(!bytes||bytes<=0)return'0 GB';return (bytes/(1024*1024*1024)).toFixed(2)+' GB';}"
"let mqttUsers=[];"
"function renderStatus(j){setTxt('status_raw',JSON.stringify(j,null,2));setTxt('status_ssid',j.wifi.ssid||'n/a');setTxt('status_ip',j.wifi.sta_ip||'none');const sd=j.sd||{};if(sd.ok){setTxt('status_sd_size',`${humanGb(sd.total)} / free ${humanGb(sd.free)}`);}else{setTxt('status_sd_size','No card');}const mem=j.mem||{};const dram=mem.dram||{};const psram=mem.psram||{};setTxt('status_ram',dram.total_kb?`${dram.free_kb||0} / ${dram.total_kb} KB`:'n/a');setTxt('status_psram',psram.total_kb?`${psram.free_kb||0} / ${psram.total_kb} KB`:'n/a');setTxt('status_clients',j.clients?j.clients.total:0);const webUserInput=document.getElementById('web_user');if(webUserInput){webUserInput.value=(j.web&&j.web.username)||'';}const operatorUser=document.getElementById('op_user');if(operatorUser){operatorUser.value=(j.web&&j.web.operator&&j.web.operator.username)||'';}const operatorToggle=document.getElementById('op_enabled');if(operatorToggle){operatorToggle.checked=!!(j.web&&j.web.operator&&j.web.operator.enabled);}const diagBox=document.getElementById('diag_verbose');if(diagBox){diagBox.checked=!!(j.diag&&j.diag.verbose_logging);}renderUidMonitor(j.uid_monitor||[]);renderSensors(j.sensors||[]);}"
"function renderUidMonitor(list){const card=document.getElementById('uid_card');const wrap=document.getElementById('uid_monitor_list');if(!card||!wrap)return;if(!Array.isArray(list)||!list.length){card.style.display='none';wrap.innerHTML='';return;}card.style.display='block';wrap.innerHTML=list.map(dev=>{const title=escapeHtml(dev.name||dev.id||'Device');const slots=(dev.slots||[]).map(slot=>{const label=escapeHtml(slot.label||slot.source||`Slot ${slot.index||0}`);const value=slot.last_value?escapeHtml(slot.last_value):'&mdash;';return `<div class=\"uid-slot\"><span class=\"label\">${label}</span><strong>${value}</strong></div>`;}).join('')||\"<div class='muted small'>No slots</div>\";return `<div class=\"uid-device\"><h4>${title}</h4><div class=\"uid-slots\">${slots}</div></div>`;}).join('');}"
"function renderSensors(list){const grid=document.getElementById('sensor_cards');const empty=document.getElementById('sensor_empty');if(!grid||!empty)return;const role=(window.__WEB_SESSION&&window.__WEB_SESSION.role)||'admin';const showAll=role!=='user';const sensors=Array.isArray(list)?list.filter(s=>s&&(showAll||s.display!==false)):[];if(!sensors.length){grid.innerHTML='';empty.style.display='block';return;}empty.style.display='none';const fmtValue=(sensor)=>{if(sensor&&typeof sensor.value==='number'){const dec=(typeof sensor.decimals==='number'&&sensor.decimals>=0&&sensor.decimals<=6)?sensor.decimals:1;return Number(sensor.value).toFixed(dec);}return'n/a';};const statusClass=status=>{switch(status){case'warn':return'status-warn';case'alarm':return'status-alarm';case'ok':return'status-ok';default:return'status-unknown';}};const describeThreshold=(label,th,sensor)=>{if(!th||!th.enabled)return'';const cmp=th.compare==='below_or_equal'?'≤':'≥';const dec=(typeof sensor.decimals==='number'&&sensor.decimals>=0&&sensor.decimals<=6)?sensor.decimals:1;const val=typeof th.value==='number'?Number(th.value).toFixed(dec):'';const units=sensor.units?` ${escapeHtml(sensor.units)}`:'';const scenario=th.scenario?` <span class='muted'>→ ${escapeHtml(th.scenario)}</span>`:'';return `<div class='sensor-thresholds-line'><span class='label'>${label}</span><span>${cmp} ${val}${units}${scenario}</span></div>`;};const renderHistory=sensor=>{if(!Array.isArray(sensor.history)||!sensor.history.length)return'';const dec=(typeof sensor.decimals==='number'&&sensor.decimals>=0&&sensor.decimals<=6)?sensor.decimals:1;const samples=sensor.history.slice(-4).reverse();const chips=samples.map(sample=>{const value=typeof sample.value==='number'?sample.value.toFixed(dec):'n/a';const ts=typeof sample.timestamp_ms==='number'?Math.round(sample.timestamp_ms/1000):'~';return `<span class=\"history-chip ${statusClass(sample.status)}\" title=\"t+${ts}s\">${value}${sensor.units?` ${escapeHtml(sensor.units)}`:''}</span>`;}).join('');return `<div class='sensor-history'>${chips}</div>`;};sensors.sort((a,b)=>{const an=(a.name||a.device||a.topic||'').toLowerCase();const bn=(b.name||b.device||b.topic||'').toLowerCase();return an.localeCompare(bn);});grid.innerHTML=sensors.map(sensor=>{const status=String(sensor.status||'unknown');const cls=statusClass(status);const units=sensor.units?`<span class='sensor-units'>${escapeHtml(sensor.units)}</span>`:'';const topic=sensor.topic?`<div class='sensor-topic'>${escapeHtml(sensor.topic)}</div>`:'';const desc=sensor.description?`<div class='muted small'>${escapeHtml(sensor.description)}</div>`:'';const updated=typeof sensor.updated_ms==='number'?`t+${Math.round(sensor.updated_ms/1000)}s`:'n/a';const thresholds=[describeThreshold('Warn',sensor.warn,sensor),describeThreshold('Alarm',sensor.alarm,sensor)].filter(Boolean).join('');const history=renderHistory(sensor);return `<div class=\"sensor-card ${cls}\"><div class='sensor-header'><div><div class='sensor-name'>${escapeHtml(sensor.name||sensor.device||'Sensor')}</div>${topic}${desc}</div><span class='sensor-status-pill ${cls}'>${status.toUpperCase()}</span></div><div class='sensor-value'>${fmtValue(sensor)}${units}</div><div class='sensor-meta'><span>Updated ${updated}</span></div>${thresholds?`<div class='sensor-thresholds'>${thresholds}</div>`:''}${history}</div>`;}).join('');}"
"function renderMqttUsers(list){mqttUsers=Array.isArray(list)?list.map(u=>({client_id:u&&u.client_id?u.client_id:'',username:u&&u.username?u.username:'',password:u&&u.password?u.password:''})):[];const wrap=document.getElementById('mqtt_users_list');if(!wrap)return;if(!mqttUsers.length){wrap.innerHTML=\"<div class='muted small'>No users configured.</div>\";return;}wrap.innerHTML=mqttUsers.map((user,idx)=>`<div class=\"mqtt-user-row\"><input placeholder=\"Client ID\" value=\"${escapeHtml(user.client_id)}\" oninput=\"updateMqttUser(${idx},'client_id',this.value)\"><input placeholder=\"Username\" value=\"${escapeHtml(user.username)}\" oninput=\"updateMqttUser(${idx},'username',this.value)\"><input placeholder=\"Password\" value=\"${escapeHtml(user.password)}\" oninput=\"updateMqttUser(${idx},'password',this.value)\"><button type=\"button\" onclick=\"removeMqttUser(${idx})\">Remove</button></div>`).join('');}"
"function addMqttUser(){mqttUsers.push({client_id:'',username:'',password:''});renderMqttUsers(mqttUsers);}"
"function updateMqttUser(idx,field,value){if(!mqttUsers[idx])return;mqttUsers[idx][field]=value;}"
"function removeMqttUser(idx){if(idx<0||idx>=mqttUsers.length)return;mqttUsers.splice(idx,1);renderMqttUsers(mqttUsers);}"
"function saveMqttUsers(){const sanitized=mqttUsers.map(u=>({client_id:(u.client_id||'').trim(),username:(u.username||'').trim(),password:(u.password||'').trim()})).filter(u=>u.client_id&&u.username&&u.password);fetch('/api/config/mqtt_users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(sanitized)}).then(r=>r.text()).then(alert).then(()=>loadStatus());}"
        "let rawShown=false;"
        "function toggleRaw(){rawShown=!rawShown;const pre=document.getElementById('status_raw');const btn=document.getElementById('status_raw_btn');if(pre){pre.style.display=rawShown?'block':'none';}if(btn){btn.textContent=rawShown?'Hide raw':'Show raw';}}"
"function loadStatus(){setTxt('status_state','Loading...');return fetch('/api/status').then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(j=>{renderStatus(j);setTxt('status_state','Updated');document.getElementById('ssid').value=j.wifi.ssid;document.getElementById('host').value=j.wifi.host;document.getElementById('mqtt_id').value=j.mqtt.id;document.getElementById('mqtt_port').value=j.mqtt.port;document.getElementById('mqtt_keep').value=j.mqtt.keepalive;renderMqttUsers((j.mqtt&&j.mqtt.users)||[]);updateAudioFromStatus(j.audio||{});updateBanner(j);if(j.wifi.sta_ip && j.wifi.sta_ip.length>0 && j.wifi.ap && !apPopupShown){apPopupShown=true;alert('Connected. IP: '+j.wifi.sta_ip+'\\nDisabling AP.');fetch('/api/ap/stop');}}).catch(err=>{setTxt('status_state','Failed to load');setTxt('status_raw',err.message);});}"
        "function saveWifi(){const s=ssid.value,p=pass.value,h=host.value;fetch(`/api/config/wifi?ssid=${encodeURIComponent(s)}&password=${encodeURIComponent(p)}&host=${encodeURIComponent(h)}`).then(r=>r.text()).then(alert);}"
        "function scanWifi(){fetch('/api/wifi/scan').then(r=>r.json()).then(list=>{const c=document.getElementById('wifi_list');c.innerHTML='';list.forEach(name=>{const d=document.createElement('div');d.className='pill';d.textContent=name;d.onclick=()=>{ssid.value=name;};c.appendChild(d);});});}"
"function saveMqtt(){const id=mqtt_id.value,port=mqtt_port.value,keep=mqtt_keep.value;fetch(`/api/config/mqtt?id=${encodeURIComponent(id)}&port=${port}&keepalive=${keep}`).then(r=>r.text()).then(alert);}"
"function saveWebPassword(){const user=(document.getElementById('web_user').value||'').trim();const current=document.getElementById('web_pass_current').value;const next=document.getElementById('web_pass_new').value;const status=document.getElementById('web_auth_status');if(!current||!next){status.textContent='Fill current and new password.';return;}status.textContent='Saving...';fetch('/api/auth/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role:'admin',username:user,current_password:current,new_password:next})}).then(res=>{if(res.status===401){throw new Error('Current password is invalid.');}if(!res.ok){throw new Error('Failed to save.');}status.textContent='Updated. Please log in again.';document.getElementById('web_pass_current').value='';document.getElementById('web_pass_new').value='';setTimeout(()=>{window.location='/login';},800);}).catch(err=>{status.textContent=err.message||'Failed';});}"
"function saveOperatorAccount(){const username=(document.getElementById('op_user').value||'').trim();const password=document.getElementById('op_pass').value;const enabled=document.getElementById('op_enabled').checked;const adminCurrent=document.getElementById('op_admin_current').value;const status=document.getElementById('op_auth_status');if(!adminCurrent){status.textContent='Enter admin password.';return;}if(enabled&&(!username||!password)){status.textContent='Operator username/password required.';return;}status.textContent='Saving...';const payload={role:'user',current_password:adminCurrent,enabled:enabled};if(enabled){payload.username=username;payload.new_password=password;}fetch('/api/auth/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(res=>{if(res.status===401){throw new Error('Admin password invalid.');}if(!res.ok){throw new Error('Failed to save.');}status.textContent=enabled?'Operator account updated.':'Operator login disabled.';document.getElementById('op_pass').value='';document.getElementById('op_admin_current').value='';if(!enabled){document.getElementById('op_user').value='';}}).catch(err=>{status.textContent=err.message||'Failed';});}"
"function logout(){fetch('/api/auth/logout',{method:'POST'}).finally(()=>{window.location='/login';});}"
"const PROGRESS_MAX=10000;"
"const PAD_GRADIENT_START={h:285,s:0.65,l:0.72};"
"const PAD_GRADIENT_END={h:48,s:0.9,l:0.7};"
"let padColorRaf=0;"
"function schedulePadColorUpdate(){if(padColorRaf){cancelAnimationFrame(padColorRaf);}padColorRaf=requestAnimationFrame(()=>{padColorRaf=0;applyPadColumnPalette();});}"
"function applyPadColumnPalette(){const wrap=document.getElementById('audio_files');if(!wrap)return;const cards=wrap.querySelectorAll('.track-card');if(!cards.length)return;const columns=new Map();cards.forEach(card=>{const key=Math.round(card.offsetLeft);if(!columns.has(key)){columns.set(key,[]);}columns.get(key).push(card);});const positions=Array.from(columns.keys()).sort((a,b)=>a-b);const palette=createPadGradient(positions.length);positions.forEach((pos,idx)=>{const base=palette[idx];const border=adjustPadLightness(base,-0.15);const glow=colorToHsla(base,0.55);columns.get(pos).forEach(card=>{card.style.setProperty('--pad-color',colorToCss(base));card.style.setProperty('--pad-border',colorToCss(border));card.style.setProperty('--pad-glow',glow);});});}"
"function createPadGradient(count){if(count<=0)return[];const out=[];for(let i=0;i<count;i++){const t=count===1?0:i/(count-1);out.push({h:lerp(PAD_GRADIENT_START.h,PAD_GRADIENT_END.h,t),s:lerp(PAD_GRADIENT_START.s,PAD_GRADIENT_END.s,t),l:lerp(PAD_GRADIENT_START.l,PAD_GRADIENT_END.l,t)});}return out;}"
"function lerp(a,b,t){return a+(b-a)*t;}"
"function adjustPadLightness(color,delta){return{h:color.h,s:color.s,l:Math.max(0,Math.min(1,color.l+delta))};}"
"function colorToCss(color){return`hsl(${Math.round(color.h)}, ${Math.round(color.s*100)}%, ${Math.round(color.l*100)}%)`;}"
"function colorToHsla(color,alpha){const a=Math.max(0,Math.min(1,typeof alpha==='number'?alpha:1));return`hsla(${Math.round(color.h)}, ${Math.round(color.s*100)}%, ${Math.round(color.l*100)}%, ${a})`;}"
"window.addEventListener('resize',()=>schedulePadColorUpdate());"
"const TRACK_LIST_ID='track_lookup';"
"function updateTrackLookupOptions(files){const list=document.getElementById(TRACK_LIST_ID);if(!list){return;}list.innerHTML='';if(!Array.isArray(files)||!files.length){return;}const groups={};files.forEach(entry=>{if(!entry||!entry.path)return;const dir=audioDirName(entry.path);if(!groups[dir]){groups[dir]=[];}groups[dir].push(entry.path);});Object.keys(groups).sort((a,b)=>a.localeCompare(b)).forEach(dir=>{const header=document.createElement('option');header.value='';header.disabled=true;header.textContent=dir||'/';list.appendChild(header);groups[dir].sort((a,b)=>audioBaseName(a).localeCompare(audioBaseName(b))).forEach(path=>{const opt=document.createElement('option');opt.value=path;opt.textContent=audioBaseName(path);opt.label=`${dir||'/'} / ${audioBaseName(path)}`;list.appendChild(opt);});});}"
"const SEEK_DEBOUNCE_MS=150;"
"const SEEK_ACK_THRESHOLD=50;"
"const SEEK_MAX_HOLD_MS=2000;"
        "let audioPlaying=false;"
        "let audioPaused=false;"
        "let currentPlayingPath='';"
        "let lastPlayedPath='';"
        "let pendingTrackPath='';"
        "let repeatOne=false;"
        "let repeatInFlight=false;"
        "let progressScrubbing=false;"
"let seekTimer=null;"
"let seekQueuedValue=null;"
"let seekPending=false;"
"let seekReleaseTimer=null;"
"let seekLastTargetMs=null;"
        "function refreshModeButtons(){}"
        "function play(path){const p=path||audio_path.value; if(!p){alert('Select a track');return;}"
        " setFileStatus('Playing...',false);"
        " resetProgressUI(true);"
        " pendingTrackPath=p;"
        " lastPlayedPath=p;"
        " repeatInFlight=false;"
        " const start=()=>fetch(`/api/audio/play?path=${encodeURIComponent(p)}&volume=${audio_vol.value}`).then(r=>r.text()).then(()=>{audioPlaying=true;audioPaused=false;currentPlayingPath=p;setFileStatus('Playing',false);markPlayingCard();}).catch(()=>setFileStatus('Play failed',true));"
        " if(currentPlayingPath){fetch('/api/audio/stop').catch(()=>{}).finally(()=>{start();});}else{start();}"
        "}"
        "function pauseAudio(){fetch('/api/audio/pause').then(()=>{audioPaused=true;setFileStatus('Paused',false);updatePauseBtn();}).catch(()=>setFileStatus('Pause failed',true));}"
        "function resumeAudio(){fetch('/api/audio/resume').then(()=>{audioPaused=false;setFileStatus('Playing',false);updatePauseBtn();}).catch(()=>setFileStatus('Resume failed',true));}"
        "function togglePause(){if(audioPaused){resumeAudio();}else{pauseAudio();}}"
        "function updatePauseBtn(){const btn=document.getElementById('audio_pause_btn');if(!btn)return;btn.title=audioPaused?'Resume':'Pause';if(audioPaused){btn.classList.add('icon-play');btn.classList.remove('icon-pause');}else{btn.classList.add('icon-pause');btn.classList.remove('icon-play');}}"
        "function stopPlay(){fetch('/api/audio/stop').then(()=>{audioPlaying=false;audioPaused=false;currentPlayingPath='';lastPlayedPath='';pendingTrackPath='';repeatInFlight=false;markPlayingCard();setFileStatus('Stopped',false);resetProgressUI(true);updatePauseBtn();}).catch(()=>setFileStatus('Stop failed',true));}"
"function setVolume(v){volInput(v,true);}"
"function publishMsg(){fetch(`/api/publish?topic=${encodeURIComponent(pub_topic.value)}&payload=${encodeURIComponent(pub_payload.value)}`).then(r=>r.text());}"
"function saveDiagnostics(){const box=document.getElementById('diag_verbose');if(!box){return;}const flag=box.checked?1:0;fetch(`/api/config/logging?verbose=${flag}`).then(r=>r.text()).then(alert).then(()=>loadStatus()).catch(()=>{});}"
"let audioCurrentDir='/sdcard';"
"let audioVolumeTimer=null;"
"let audioDurationMs=0;"
"let audioPosMs=0;"
"function setFileStatus(msg,isError){const el=document.getElementById('audio_status');if(!el)return;el.textContent=msg||'';el.style.color=isError?'#f87171':'#94a3b8';}"
"function audioBaseName(path){if(!path)return'';const parts=path.split('/').filter(Boolean);return parts.length?parts[parts.length-1]:path;}"
"function audioDirName(path){if(!path)return'/';const idx=path.lastIndexOf('/');if(idx<0)return'/';const dir=path.slice(0,idx)||'/';return dir||'/';}"
"function renderAudioListing(list){const folders=(Array.isArray(list)?list:[]).filter(item=>item&&item.dir);const files=(Array.isArray(list)?list:[]).filter(item=>item&&!item.dir);const folderWrap=document.getElementById('audio_folders');const fileWrap=document.getElementById('audio_files');if(folderWrap){folderWrap.innerHTML='';if(!folders.length){const empty=document.createElement('div');empty.className='muted small';empty.textContent='No folders';folderWrap.appendChild(empty);}else{folders.sort((a,b)=>audioBaseName(a.path).localeCompare(audioBaseName(b.path)));folders.forEach(entry=>{const chip=document.createElement('div');chip.className='folder-chip';chip.textContent=audioBaseName(entry.path);chip.onclick=()=>loadFiles(entry.path);folderWrap.appendChild(chip);});}}if(fileWrap){fileWrap.innerHTML='';if(!files.length){const empty=document.createElement('div');empty.className='muted small';empty.textContent='No tracks';fileWrap.appendChild(empty);}else{files.sort((a,b)=>audioBaseName(a.path).localeCompare(audioBaseName(b.path)));files.forEach(entry=>{const card=document.createElement('div');card.className='track-card';card.dataset.path=entry.path;const label=document.createElement('div');label.className='track-name';label.textContent=audioBaseName(entry.path);card.appendChild(label);card.onclick=()=>selectTrack(entry.path,card);fileWrap.appendChild(card);});schedulePadColorUpdate();}}const label=document.getElementById('path_label');if(label){label.textContent=audioCurrentDir;}updateTrackLookupOptions(files);markPlayingCard();}"
"function selectTrack(path,card){const input=document.getElementById('audio_path');if(input){input.value=path||'';}document.querySelectorAll('#audio_files .track-card.selected').forEach(el=>el.classList.remove('selected'));if(card){card.classList.add('selected');}const shouldAutoPlay=!!(path&&(!audioPlaying||path!==currentPlayingPath));setFileStatus(path?('Selected '+audioBaseName(path)):'No track',false);if(shouldAutoPlay){play(path);}}"
"function markPlayingCard(){const cards=document.querySelectorAll('#audio_files .track-card');cards.forEach(card=>{if(card.dataset.path===currentPlayingPath){card.classList.add('playing');}else{card.classList.remove('playing');}});}"
"function loadFiles(path){const target=path||audioCurrentDir||'/sdcard';setFileStatus('Loading...',false);const url='/api/files?path='+encodeURIComponent(target);return fetch(url).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(list=>{audioCurrentDir=target;renderAudioListing(list);setFileStatus('Loaded',false);return list;}).catch(err=>{setFileStatus(err.message||'Load failed',true);throw err;});}"
"function navUp(){if(!audioCurrentDir||audioCurrentDir==='/sdcard'){return;}const idx=audioCurrentDir.lastIndexOf('/');const next=idx>7?audioCurrentDir.slice(0,idx):'/sdcard';loadFiles(next);}"
"function formatMs(ms){if(!ms||ms<=0)return'0:00';const total=Math.floor(ms/1000);const m=Math.floor(total/60);const s=total%60;return m+':' + (s<10?'0'+s:s);}"
"function updateProgressDisplay(posMs,durMs){const slider=document.getElementById('audio_prog');const text=document.getElementById('audio_prog_txt');const pos=typeof posMs==='number'?posMs:audioPosMs;const dur=typeof durMs==='number'?durMs:audioDurationMs;if(slider&&!progressScrubbing){const ratio=dur>0?Math.max(0,Math.min(1,pos/(dur||1))):0;slider.value=Math.floor(ratio*PROGRESS_MAX);}if(text){const durText=dur>0?formatMs(dur):'?';text.textContent=formatMs(pos)+' / '+durText;}}"
"function resetProgressUI(clear){if(clear){audioDurationMs=0;}audioPosMs=0;updateProgressDisplay(0,clear?0:audioDurationMs);}"
"function updateAudioFromStatus(stat){if(!stat)return;audioPlaying=!!stat.playing;audioPaused=!!stat.paused;audioDurationMs=stat.dur_ms||0;audioPosMs=stat.pos_ms||0;if(typeof stat.volume==='number'){const slider=document.getElementById('audio_vol');if(slider){slider.value=stat.volume;}volInput(stat.volume,true);}if(stat.path){currentPlayingPath=stat.path;lastPlayedPath=stat.path;}setFileStatus(stat.message||(audioPlaying?'Playing':'Idle'),false);updateProgressDisplay();markPlayingCard();updatePauseBtn();}"
"function volInput(val,fromStatus){const display=document.getElementById('audio_vol_val');if(display){display.textContent=val;}if(fromStatus){return;}if(audioVolumeTimer){clearTimeout(audioVolumeTimer);}audioVolumeTimer=setTimeout(()=>{fetch('/api/audio/volume?val='+encodeURIComponent(val)).catch(()=>{});},200);}"
"function scrubPreview(value){const raw=parseInt(value,10)||0;const ratio=Math.max(0,Math.min(1,raw/PROGRESS_MAX));const preview=Math.floor(ratio*(audioDurationMs||0));const text=document.getElementById('audio_prog_txt');if(text){const dur=audioDurationMs>0?formatMs(audioDurationMs):'?';text.textContent=formatMs(preview)+' / '+dur;}scheduleSeek(raw);}"
"function scheduleSeek(value){if(!audioDurationMs)return;const next=typeof value==='number'?value:parseInt(value,10);if(Number.isNaN(next))return;seekQueuedValue=next;if(seekTimer){clearTimeout(seekTimer);}seekTimer=setTimeout(()=>commitScrub(),SEEK_DEBOUNCE_MS);if(seekReleaseTimer){clearTimeout(seekReleaseTimer);}seekReleaseTimer=setTimeout(()=>commitScrub(),SEEK_MAX_HOLD_MS);}"
"function commitScrub(value){const raw=(typeof value!=='undefined'&&value!==null)?value:seekQueuedValue;const sliderVal=typeof raw==='number'?raw:parseInt(raw,10);if(seekTimer){clearTimeout(seekTimer);seekTimer=null;}if(seekReleaseTimer){clearTimeout(seekReleaseTimer);seekReleaseTimer=null;}if(!audioDurationMs||sliderVal===null||Number.isNaN(sliderVal))return;seekQueuedValue=sliderVal;if(seekPending)return;const ratio=Math.max(0,Math.min(1,sliderVal/PROGRESS_MAX));const target=Math.floor(ratio*audioDurationMs);if(seekLastTargetMs!==null&&Math.abs(target-seekLastTargetMs)<SEEK_ACK_THRESHOLD){seekQueuedValue=null;return;}seekQueuedValue=null;seekPending=true;fetch(`/api/audio/seek?pos=${target}`).then(()=>{audioPosMs=target;updateProgressDisplay();seekLastTargetMs=target;}).catch(()=>{setFileStatus('Seek failed',true);seekLastTargetMs=null;}).finally(()=>{seekPending=false;if(seekQueuedValue!==null){commitScrub();}});}"
"function startScrub(){progressScrubbing=true;}"
"function finishScrub(){progressScrubbing=false;updateProgressDisplay();commitScrub();}"
        "let statusInterval=null;"
"function fetchAudioStatus(){return fetch('/api/status').then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(j=>{if(j.audio){updateAudioFromStatus(j.audio);}if(j.sensors){renderSensors(j.sensors);}}).catch(()=>{});}"
        "function toggleRepeat(){repeatOne=!repeatOne;const btn=document.getElementById('audio_repeat_btn');if(btn){if(repeatOne){btn.classList.add('active');}else{btn.classList.remove('active');}}}"
        "refreshModeButtons();"
"sessionRolePromise.then(()=>{loadStatus().then(()=>{if(statusInterval)clearInterval(statusInterval);statusInterval=setInterval(()=>{const activePane=document.querySelector('.pane.active');if(!activePane)return;const activeId=activePane.id;if(activeId==='pane-status'||activeId==='pane-audio'||activeId==='pane-monitor'){fetchAudioStatus();}},3000);});});"
"</script><script src='/ui/devices.js?v=4'></script>"
        "</div>"
        "</body></html>";

static const char s_web_ui_login[] =
"<!DOCTYPE html><html><head><meta charset='utf-8'><title>Broker Login</title>"
"<style>"
"body{margin:0;padding:0;font-family:Arial,sans-serif;background:#05070b;color:#f1f5f9;display:flex;align-items:center;justify-content:center;height:100vh;}"
".card{background:#0b0f17;border:1px solid #1f2430;border-radius:16px;padding:30px;width:90%;max-width:360px;box-shadow:0 20px 60px rgba(0,0,0,0.45);}"
".card h2{margin:0 0 18px;font-weight:700;text-align:center;}"
".card label{display:block;font-size:13px;color:#94a3b8;margin-top:12px;margin-bottom:4px;}"
".card input,.card select{width:100%;padding:10px 12px;border-radius:10px;border:1px solid #1f2430;background:#080b14;color:#f1f5f9;}"
".card button{width:100%;margin-top:18px;background:#3b82f6;color:#fff;border:none;border-radius:10px;padding:12px;font-weight:600;cursor:pointer;box-shadow:0 12px 30px rgba(59,130,246,0.35);}"
".card button:hover{background:#2563eb;}"
".muted{color:#94a3b8;font-size:13px;margin-top:12px;text-align:center;}"
".error{color:#f97316;font-size:13px;margin-top:8px;text-align:center;min-height:18px;}"
"</style></head><body>"
"<div class='card'><h2>Broker Login</h2>"
"<form id='login_form'>"
"<label for='login_user'>Username</label><input id='login_user' autocomplete='username' required>"
"<label for='login_pass'>Password</label><input id='login_pass' type='password' autocomplete='current-password' required>"
"<label for='login_role'>Role</label>"
"<select id='login_role'>"
"<option value='admin'>Administrator</option>"
"<option value='user'>Scenario operator</option>"
"</select>"
"<button type='submit'>Sign in</button>"
"<div id='login_status' class='error'></div>"
"<div class='muted'>Forgot password? Hold the reset pin LOW for 10s.</div>"
"</form></div>"
"<script>"
"const form=document.getElementById('login_form');"
"form.addEventListener('submit',async ev=>{ev.preventDefault();const username=document.getElementById('login_user').value.trim();const password=document.getElementById('login_pass').value;const role=document.getElementById('login_role').value;const status=document.getElementById('login_status');status.textContent='';try{const res=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password,role})});if(res.ok){const next=new URLSearchParams(window.location.search).get('next')||'/';window.location=next;return;}if(res.status===423){status.textContent='Web UI locked. Try again later.';}else{status.textContent='Invalid credentials.';}}catch(err){status.textContent='Network error.';}});"
"</script></body></html>";

const char *web_ui_get_index_html(void)
{
    return s_web_ui_index;
}

const char *web_ui_get_login_html(void)
{
    return s_web_ui_login;
}
