#include "web_ui_page.h"

static const char s_web_ui_index[] =
"<!DOCTYPE html><html><head><meta charset='utf-8'><title>Broker</title>"
        "<style>"
        "body{margin:0;padding:0;font-family:Arial,sans-serif;background:#0b0d12;color:#e6e7ea;display:flex;justify-content:center;}"
        ".page{width:100%;max-width:1400px;margin:0 auto;}"
        "header{padding:18px 24px;border-bottom:1px solid #181c26;background:#0f1219;position:sticky;top:0;display:flex;justify-content:center;z-index:40;}"
        ".tabs{display:flex;flex-wrap:wrap;--tab-gap:10px;gap:var(--tab-gap);padding:10px 12px;background:#0f1219;border:1px solid #181c26;border-radius:12px;margin:0 auto 12px;width:100%;max-width:1200px;justify-content:center;}"
        ".tab{height:42px;flex:0 0 calc((100% - 7*var(--tab-gap))/8);max-width:calc((100% - 7*var(--tab-gap))/8);min-width:100px;padding:0 12px;border-radius:12px;cursor:pointer;border:2px solid var(--tab-color,#121621);background:var(--tab-color,#121621);color:#0b0d13;font-weight:600;display:inline-flex;align-items:center;justify-content:center;gap:8px;font-size:13px;box-shadow:0 6px 18px rgba(0,0,0,0.3);transition:transform .15s ease,box-shadow .2s ease,opacity .2s ease;}"
        ".tab:not(.active){opacity:0.88;}"
        ".tab.active{transform:translateY(-1px);box-shadow:0 10px 26px rgba(0,0,0,0.45),0 0 0 2px rgba(255,255,255,0.2);}"
        ".tab .tab-icon{width:20px;height:20px;border-radius:8px;background:rgba(11,13,19,0.15);display:inline-flex;align-items:center;justify-content:center;background-repeat:no-repeat;background-position:center;background-size:16px;color:#0b0d13;flex-shrink:0;}"
        ".tab .tab-label{white-space:nowrap;}"
        ".tab[data-icon='status'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25230b0d13%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Cpolyline%20points%3D%273%2012%207%2012%2010%206%2014%2018%2017%2012%2021%2012%27%2F%3E%3C%2Fsvg%3E\");}"
        ".tab[data-icon='audio'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25230b0d13%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Cpolygon%20points%3D%275%209%209%209%2013%205%2013%2019%209%2015%205%2015%205%209%27%2F%3E%3Cpath%20d%3D%27M16%209c1.5%201.5%201.5%204.5%200%206%27%2F%3E%3Cpath%20d%3D%27M19%207c2.5%202.5%202.5%207.5%200%2010%27%2F%3E%3C%2Fsvg%3E\");}"
        ".tab[data-icon='pictures'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25230b0d13%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Crect%20x%3D%273%27%20y%3D%275%27%20width%3D%2718%27%20height%3D%2714%27%20rx%3D%272%27%2F%3E%3Ccircle%20cx%3D%278.5%27%20cy%3D%2710%27%20r%3D%271.5%27%2F%3E%3Cpath%20d%3D%27M21%2015l-5-5-4%204-2-2-5%205%27%2F%3E%3C%2Fsvg%3E\");}"
        ".tab[data-icon='laser'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25230b0d13%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Ccircle%20cx%3D%2712%27%20cy%3D%2712%27%20r%3D%277%27%2F%3E%3Ccircle%20cx%3D%2712%27%20cy%3D%2712%27%20r%3D%272%27%2F%3E%3Cline%20x1%3D%2712%27%20y1%3D%273%27%20x2%3D%2712%27%20y2%3D%271%27%2F%3E%3Cline%20x1%3D%2712%27%20y1%3D%2723%27%20x2%3D%2712%27%20y2%3D%2721%27%2F%3E%3Cline%20x1%3D%273%27%20y1%3D%2712%27%20x2%3D%271%27%20y2%3D%2712%27%2F%3E%3Cline%20x1%3D%2723%27%20y1%3D%2712%27%20x2%3D%2721%27%20y2%3D%2712%27%2F%3E%3C%2Fsvg%3E\");}"
        ".tab[data-icon='robot'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25230b0d13%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Crect%20x%3D%275%27%20y%3D%279%27%20width%3D%2714%27%20height%3D%2710%27%20rx%3D%272%27%2F%3E%3Ccircle%20cx%3D%279%27%20cy%3D%2713%27%20r%3D%271%27%2F%3E%3Ccircle%20cx%3D%2715%27%20cy%3D%2713%27%20r%3D%271%27%2F%3E%3Cpath%20d%3D%27M8%2017h8%27%2F%3E%3Cpath%20d%3D%27M12%205V3%27%2F%3E%3C%2Fsvg%3E\");}"
        ".tab[data-icon='settings'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25230b0d13%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Ccircle%20cx%3D%2712%27%20cy%3D%2712%27%20r%3D%273%27%2F%3E%3Cpath%20d%3D%27M19.4%2015a1.65%201.65%200%200%200%20.33%201.82l.06.06a2%202%200%200%201-2.83%202.83l-.06-.06a1.65%201.65%200%200%200-1.82-.33%201.65%201.65%200%200%200-1%201.51V21a2%202%200%200%201-4%200v-.09A1.65%201.65%200%200%200%209%2019.4a1.65%201.65%200%200%200-1.82.33l-.06.06a2%202%200%200%201-2.83-2.83l.06-.06a1.65%201.65%200%200%200%20.33-1.82%201.65%201.65%200%200%200-1.51-1H3a2%202%200%200%201%200-4h.09A1.65%201.65%200%200%200%204.6%209%201.65%201.65%200%200%200%204.27%207.18l-.06-.06A2%202%200%200%201%207.04%204.3l.06.06A1.65%201.65%200%200%200%208.91%204a1.65%201.65%200%200%200%201-1.51V3a2%202%200%200%201%204%200v.09A1.65%201.65%200%200%200%2015%204.6a1.65%201.65%200%200%200%201.82-.33l.06-.06a2%202%200%200%201%202.83%202.83l-.06.06A1.65%201.65%200%200%200%2019.74%209%201.65%201.65%200%200%200%2021.25%2010H21a2%202%200%200%201%200%204h-.09a1.65%201.65%200%200%200-1.51%201z%27%2F%3E%3C%2Fsvg%3E\");}"
        ".tab[data-icon='devices'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25230b0d13%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Cpath%20d%3D%27M12%201V7%27/%3E%3Crect%20x%3D%275%27%20y%3D%279%27%20width%3D%2714%27%20height%3D%2711%27%20rx%3D%272%27/%3E%3Cpath%20d%3D%27M8%2020v3h8v-3%27/%3E%3Cpath%20d%3D%27M8%2013h8%27/%3E%3Ccircle%20cx%3D%2212%22%20cy%3D%2216%22%20r%3D%221%22/%3E%3C/svg%3E\");}"
        ".tab[data-icon='network'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25230b0d13%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Cpath%20d%3D%27M5%2012a9%209%200%200%201%2014%200%27%2F%3E%3Cpath%20d%3D%27M8.5%2015.5a5%205%200%200%201%207%200%27%2F%3E%3Cpath%20d%3D%27M12%2019h.01%27%2F%3E%3C%2Fsvg%3E\");}"
        ".tab[data-icon='power'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25230b0d13%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Cline%20x1%3D%2712%27%20y1%3D%272%27%20x2%3D%2712%27%20y2%3D%2712%27%2F%3E%3Cpath%20d%3D%27M5.5%207.5a7%207%200%201%200%2013%200%27%2F%3E%3C%2Fsvg%3E\");}"
        ".pane{padding:24px;display:none;max-width:1200px;margin:0 auto;} .pane.active{display:block;}"
        ".card{background:#121621;border:1px solid #1f2430;border-radius:12px;padding:16px;margin:0 auto 14px;box-shadow:0 10px 30px rgba(0,0,0,0.25);}"
        "h3,h4{margin:0 0 10px;color:#f0f2f5;font-weight:600;}"
        "input,select{background:#0c0e12;border:1px solid #2b3344;color:#e6e7ea;border-radius:8px;padding:10px 12px;margin:4px 8px 4px 0;min-width:220px;}"
        "button:not(.icon-btn){background:#3b82f6;border:none;color:#fff;border-radius:10px;padding:10px 16px;margin:4px 8px 4px 0;cursor:pointer;font-weight:600;box-shadow:0 6px 18px rgba(59,130,246,0.35);}button:not(.icon-btn):hover{background:#2563eb;}"
        ".muted{color:#8b92a3;font-size:13px;}"
        ".row{display:flex;flex-wrap:wrap;align-items:center;}"
        ".controls-row{display:flex;align-items:center;gap:16px;flex-wrap:wrap;}"
        ".volume-control{display:flex;align-items:center;gap:10px;min-width:200px;flex:1 1 200px;}"
        ".volume-control input{max-width:220px;}"
        ".control-buttons{display:flex;gap:10px;flex-shrink:0;}"
        ".mode-row{gap:10px;}"
        ".mode-btn{min-width:120px;font-weight:600;border:2px solid #1f2430;background:#0c0e12;color:#cbd5e1;border-radius:10px;padding:10px 14px;cursor:pointer;transition:box-shadow .2s ease,border-color .2s ease,color .2s ease,background .2s ease;}"
        ".mode-btn.active{border-color:#3b82f6;background:#0f172a;color:#fff;box-shadow:0 0 12px rgba(59,130,246,0.35);}"
        ".mode-btn.mode-last{box-shadow:0 0 0 2px rgba(59,130,246,0.6),0 0 16px rgba(59,130,246,0.35);}"
        ".progress-box{border:1px solid #1f2430;border-radius:10px;background:#0c0e12;padding:8px 12px;margin-top:10px;display:flex;flex-direction:column;gap:4px;}"
        ".progress-row{display:flex;flex-direction:column;align-items:stretch;gap:2px;}"
        ".progress-row input{flex:0 0 auto;min-width:220px;width:100%;}"
        ".progress-row .muted{font-size:12px;}"
        "input[type=range]{-webkit-appearance:none;appearance:none;padding:0;background:transparent;border:none;min-width:0;height:26px;display:block;margin:4px 0;}"
        "input[type=range]:focus{outline:none;}"
        "input[type=range]::-webkit-slider-runnable-track{width:100%;height:6px;background:#1f2430;border-radius:999px;border:1px solid #2b3344;}"
        "input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;appearance:none;width:16px;height:16px;border-radius:50%;background:#3b82f6;border:2px solid #0b0d13;margin-top:-6px;box-shadow:0 0 0 2px rgba(59,130,246,0.3);cursor:pointer;}"
        "input[type=range]::-moz-range-track{width:100%;height:6px;background:#1f2430;border-radius:999px;border:1px solid #2b3344;}"
        "input[type=range]::-moz-range-thumb{width:16px;height:16px;border-radius:50%;background:#3b82f6;border:2px solid #0b0d13;cursor:pointer;}"
        "input[type=range]::-ms-track{width:100%;height:6px;background:transparent;border-color:transparent;color:transparent;}"
        "input[type=range]::-ms-fill-lower{background:#1f2430;border-radius:999px;border:1px solid #2b3344;}"
        "input[type=range]::-ms-fill-upper{background:#1f2430;border-radius:999px;border:1px solid #2b3344;}"
        "input[type=range]::-ms-thumb{width:16px;height:16px;border-radius:50%;background:#3b82f6;border:2px solid #0b0d13;cursor:pointer;margin-top:0;}"
        ".list{margin:6px 0;}"
        ".pill{display:inline-block;padding:6px 10px;border-radius:12px;background:#1f2430;margin:4px;color:#cbd5e1;font-size:13px;cursor:pointer;}"
        ".badge{display:inline-block;padding:6px 10px;border-radius:12px;background:#1f2430;margin-left:8px;font-size:12px;}"
        ".hero{padding:16px 24px;background:#0f1219;border:1px solid #181c26;border-radius:12px;margin:0 auto 12px;max-width:1200px;display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap;}"
        ".hero h2{margin:0;font-weight:700;color:#f0f2f5;}"
        ".hero .status-clusters{display:flex;gap:16px;align-items:center;flex-wrap:wrap;margin-left:auto;}"
        ".device-cluster{display:flex;align-items:center;gap:6px;background:#0c0e12;border:1px solid #1f2430;padding:6px 10px;border-radius:10px;min-width:110px;justify-content:center;}"
        ".device-cluster .label{font-size:12px;color:#8b92a3;display:flex;align-items:center;gap:4px;}"
        ".device-cluster .dots{display:flex;gap:4px;}"
        ".device-cluster .dots span{width:10px;height:10px;border-radius:50%;background:#1f2937;}"
        ".device-icon{font-size:16px;}"
        ".stat-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:10px;margin-top:12px;}"
        ".stat{background:#0c0e12;border:1px solid #1f2430;border-radius:10px;padding:10px 12px;}"
        ".stat .label{display:block;color:#8b92a3;font-size:12px;margin-bottom:4px;}"
        ".stat .value{font-weight:600;color:#e6e7ea;}"
        ".dots span{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:4px;background:#1f2937;}"
        ".small{font-size:12px;}"
        ".status-row{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin:6px 0;}"
        ".file-browser{margin-top:12px;border:1px solid #1f2430;background:#0f1219;border-radius:10px;padding:12px;max-width:1200px;margin-left:auto;margin-right:auto;}"
        ".folder-row{display:flex;flex-wrap:wrap;gap:10px;margin:10px auto;width:100%;max-width:calc(8*100px + 7*10px);justify-content:center;min-height:50px;align-items:center;}"
        ".folder-chip{width:100px;height:50px;border:3px solid #1f2430;border-radius:10px;background:#000;cursor:pointer;font-size:11px;color:#e5e7eb;display:flex;align-items:center;justify-content:center;box-sizing:border-box;overflow:hidden;text-align:center;}"
        ".folder-chip:hover{border-color:#f8fafc;}"
        ".folder-chip.active{box-shadow:0 0 0 2px #f8fafc;}"
        ".file-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(100px,1fr));grid-auto-rows:100px;gap:10px;margin:8px auto 0;width:100%;max-width:calc(8*100px + 7*10px);justify-content:center;}"
        ".track-card{border-radius:10px;width:100px;height:100px;display:flex;align-items:flex-end;justify-content:center;position:relative;overflow:hidden;color:#0b0d13;background:#111827;cursor:pointer;box-shadow:0 4px 12px rgba(0,0,0,0.35);border:3px solid transparent;z-index:1;transition:transform .15s ease,box-shadow .2s ease;}"
        ".track-card.playing{box-shadow:0 0 0 4px #3b82f6,0 0 30px rgba(59,130,246,0.9),0 0 60px rgba(59,130,246,0.35),inset 0 0 28px rgba(255,255,255,0.55);border-color:#3b82f6;z-index:3;transform:translateY(-3px);}"
        ".track-name{width:100%;text-align:center;padding:6px 4px;box-sizing:border-box;color:#0b0d13;font-weight:700;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:11px;text-shadow:0 1px 3px rgba(0,0,0,0.35);background:rgba(0,0,0,0.1);}"
        ".icon-btn{width:34px;height:34px;border:1px solid #1f2430;border-radius:8px;background:#0c0e12;color:#cbd5e1;display:inline-flex;align-items:center;justify-content:center;cursor:pointer;margin-left:12px;position:relative;}"
        ".icon-btn::before{content:'';display:block;width:14px;height:14px;}"
        ".icon-btn:hover{border-color:#3b82f6;color:#e5e7eb;}"
        ".icon-btn.active{border-color:#3b82f6;box-shadow:0 0 0 1px #3b82f6;background:#0e1220;color:#e5e7eb;}"
        ".icon-btn.icon-stop::before{width:12px;height:12px;background:#f87171;border-radius:3px;}"
        ".icon-btn.icon-pause::before{background:linear-gradient(90deg,#cbd5e1 0,#cbd5e1 40%,transparent 40%,transparent 60%,#cbd5e1 60%,#cbd5e1 100%);}"
        ".icon-btn.icon-play::before{content:'';width:0;height:0;border-left:12px solid #cbd5e1;border-top:6px solid transparent;border-bottom:6px solid transparent;margin-left:2px;}"
        ".icon-btn.icon-repeat::before{background-image:url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' stroke='%23cbd5e1' stroke-width='2' fill='none' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpolyline points='17 1 21 5 17 9'/%3E%3Cpath d='M3 11V9a4 4 0 0 1 4-4h14'/%3E%3Cpolyline points='7 23 3 19 7 15'/%3E%3Cpath d='M21 13v2a4 4 0 0 1-4 4H3'/%3E%3C/svg%3E\");background-size:contain;background-repeat:no-repeat;}"
        ".robot-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(100px,1fr));grid-auto-rows:140px;grid-gap:12px;margin-top:12px;justify-content:center;max-width:calc(8*100px + 7*12px);margin-left:auto;margin-right:auto;}"
        ".robot-slot{display:flex;flex-direction:column;gap:6px;width:100px;align-items:center;}"
        ".robot-slot-label{font-size:12px;color:#8b92a3;align-self:flex-start;}"
        ".robot-card{cursor:pointer;position:relative;}"
        ".robot-edit-btn{position:absolute;top:4px;right:4px;width:26px;height:26px;border-radius:50%;border:1px solid rgba(0,0,0,0.2);background:rgba(255,255,255,0.2);color:#0b0d13;font-weight:bold;line-height:1;display:flex;align-items:center;justify-content:center;}"
        ".pic-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(320px,1fr));gap:10px;}"
        ".pic-card{border:1px solid #1f2430;border-radius:10px;background:#0c0e12;padding:12px;display:flex;flex-direction:column;gap:8px;overflow:hidden;}"
        ".pic-uids{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;}"
        ".pic-uids input{width:100%;box-sizing:border-box;min-width:0;}"
        ".pic-last{font-size:12px;color:#8b92a3;}"
        "table{width:100%;border-collapse:collapse;margin-top:10px;}"
        "td,th{border:1px solid #1f2430;padding:8px;}"
        "@media(max-width:600px){header{padding:12px;} .pane{padding:16px;width:100%;} .card{margin:0 0 12px;width:100%;} .hero{margin:0 0 12px;padding:12px;} .row{flex-direction:column;align-items:stretch;} .row button,.row select,.row input{width:100%;max-width:100%;} .controls-row{flex-direction:column;align-items:stretch;} .control-buttons{justify-content:space-between;} .volume-control{width:100%;} .progress-row input{max-width:100%;} .file-browser{padding:10px;} .file-grid{grid-template-columns:repeat(4,minmax(0,1fr));max-width:none;} .robot-grid{grid-template-columns:repeat(4,minmax(0,1fr));max-width:none;}}"
        "</style><link rel='stylesheet' href='/ui/devices.css?v=3'></head><body>"
        "<div class='page'>"
        "<header><div class='tabs'>"
        "<div class='tab active' data-tab='status' data-icon='status'><span class='tab-icon'></span><span class='tab-label'>Status</span></div>"
        "<div class='tab' data-tab='audio' data-icon='audio'><span class='tab-icon'></span><span class='tab-label'>Audio</span></div>"
"<div class='tab' data-tab='pictures' data-icon='pictures'><span class='tab-icon'></span><span class='tab-label'>Pictures</span></div>"
"<div class='tab' data-tab='laser' data-icon='laser'><span class='tab-icon'></span><span class='tab-label'>Laser</span></div>"
"<div class='tab' data-tab='robot' data-icon='robot'><span class='tab-icon'></span><span class='tab-label'>Robot</span></div>"
"<div class='tab' data-tab='devices' data-icon='devices'><span class='tab-icon'></span><span class='tab-label'>Devices</span></div>"
"<div class='tab' data-tab='settings' data-icon='settings'><span class='tab-icon'></span><span class='tab-label'>Settings</span></div>"
"</div></header>"
        "<div class='hero'><h2>Broker</h2><div class='status-clusters'>"
        "<div class='device-cluster'><span class='label'>🖼️ Pictures</span><span id='cluster_pictures' class='dots'></span></div>"
        "<div class='device-cluster'><span class='label'>🔫 Laser</span><span id='cluster_laser' class='dots'></span></div>"
        "<div class='device-cluster'><span class='label'>🤖 Robot</span><span id='cluster_robot' class='dots'></span></div>"
        "</div><div id='banner' class='muted'>Loading status...</div></div>"
        "<div class='pane active' id='pane-status'>"
        "<div class='card'><h3>Status<span id='status_badge' class='badge'></span></h3>"
        "<div class='status-row'><button onclick='ping()'>Ping</button><button onclick='loadStatus()'>Refresh</button><button id='status_raw_btn' onclick='toggleRaw()'>Show raw</button><span id='status_state' class='muted'>Loading...</span></div>"
        "<div class='stat-grid'>"
        "<div class='stat'><span class='label'>Wi-Fi SSID</span><span id='status_ssid' class='value'>n/a</span></div>"
        "<div class='stat'><span class='label'>STA IP</span><span id='status_ip' class='value'>n/a</span></div>"
        "<div class='stat'><span class='label'>SD Size</span><span id='status_sd_size' class='value'>n/a</span></div>"
        "<div class='stat'><span class='label'>Clients total</span><span id='status_clients' class='value'>0</span></div>"
        "</div>"
        "<pre id='status_raw' class='muted small' style='display:none;'></pre>"
        "</div></div>"

        "<div class='pane' id='pane-audio'>"
        "<div class='card'><h3>Audio</h3>"
        "<input id='audio_path' type='hidden'>"
        "<div class='controls-row'><div class='volume-control'><input id='audio_vol' type='range' min='0' max='100' value='70' oninput=\"volInput(this.value)\"><span class='muted'>Volume: <span id='audio_vol_val'>70</span>%</span></div><div class='control-buttons'><button id='audio_repeat_btn' class='icon-btn icon-repeat' onclick='toggleRepeat()' title='Repeat track'></button><button id='audio_pause_btn' class='icon-btn icon-pause' onclick='togglePause()' title='Pause'></button><button id='audio_stop_btn' class='icon-btn icon-stop' onclick='stopPlay()' title='Stop'></button></div></div>"
        "<div class='progress-box'><div class='row progress-row'><input id='audio_prog' type='range' min='0' max='10000' value='0' step='1' oninput=\"scrubPreview(this.value)\" onchange=\"commitScrub(this.value)\" onmousedown=\"startScrub()\" onmouseup=\"finishScrub()\" ontouchstart=\"startScrub()\" ontouchend=\"finishScrub()\" ontouchcancel=\"finishScrub()\"><span class='muted'>Progress: <span id='audio_prog_txt'>0:00 / ?</span></span></div></div>"
        "<div id='audio_status' class='muted small'>Loading files...</div>"
        "<div class='file-browser'>"
        "<div class='row'><button onclick='navUp()'>Up</button><button onclick='loadFiles()'>Refresh files</button><span id='path_label' class='muted small'>/sdcard</span><span class='muted small'>Click track to select</span></div>"
        "<div id='audio_folders' class='folder-row' style='border:1px solid #1f2430;padding:6px 10px;border-radius:12px;background:#0d1018;margin-top:8px;min-height:50px;'></div>"
        "<div id='audio_files' class='file-grid' style='border:1px solid #1f2430;padding:10px;border-radius:12px;background:#0d1018;margin-top:8px;'></div>"
        "</div>"
        "</div></div>"

        "<div class='pane' id='pane-pictures'>"
        "<div class='card'><h3>Pictures setup</h3>"
        "<div class='row'><button onclick='loadPictures()'>Refresh</button><button onclick='saveTracks()'>Save tracks</button><button onclick='toggleAddMode(true)'>Add mode ON</button><button onclick='toggleAddMode(false)'>Add mode OFF</button><button onclick='forceCheck()'>Force check</button></div>"
        "<div class='row'><select id='track_ok_select'></select><select id='track_fail_select'></select></div>"
        "<div id='pic_status' class='muted small'></div>"
        "<div id='pic_grid' class='pic-grid'></div>"
        "</div></div>"

        "<div class='pane' id='pane-laser'>"
        "<div class='card'><h3>Laser</h3>"
        "<div class='row'><button onclick='loadLaser()'>Refresh</button><button onclick='saveLaser()'>Save</button></div>"
        "<div class='row'><button id='laser_toggle_btn' onclick='toggleLaser()'>Disable</button><span id='laser_toggle_status' class='muted small'></span></div>"
        "<div class='row'><select id='laser_hold_select'></select><select id='laser_relay_select'></select></div>"
        "<div class='row'><input id='laser_seconds' type='number' min='1' max='3600' value='20' style='max-width:160px' placeholder='Hold seconds'><select id='laser_mode' style='max-width:220px'><option value='cumulative'>Накопительный</option><option value='continuous'>Непрерывный</option></select></div>"
        "<div id='laser_status' class='muted small'></div>"
        "<div class='muted small'>Трек удержания играет пока есть heartbeat laser/laserOn, при пропадании ставится на паузу. Порог включает relay/relayOn и отправляет robot/laser/relayOn.mp3.</div>"
        "</div></div>"

        "<div class='pane' id='pane-robot'>"
        "<div class='card'>"
        "<div class='row mode-row'><button id='sarcasm_btn' class='mode-btn' onclick='toggleSarcasm()'>Sarcastic</button><button id='broken_btn' class='mode-btn' onclick='toggleBroken()'>Broken</button></div>"
        "<div class='card' style='margin-top:12px;'>"
        "<h4>Quick tracks</h4>"
        "<div class='muted small'>Tap a tile to publish /sdcard/audio/&lt;name&gt;.mp3. Use + to edit the slot.</div>"
        "<div id='robot_presets' class='robot-grid'></div>"
        "</div>"
        "<div class='card' style='margin-top:12px;'>"
        "<h4>Robot folders</h4>"
        "<div class='row'><input id='robot_laser_dir' placeholder='robot/laser dir' style='min-width:220px'><input id='robot_sarcasm_dir' placeholder='robot/mode/sarcastic dir' style='min-width:220px'><input id='robot_broken_dir' placeholder='robot/broken dir' style='min-width:220px'></div>"
        "<div class='row'><button onclick='saveRobotCfg()'>Save</button></div>"
        "<div id='robot_status' class='muted small'></div>"
        "</div>"
        "</div></div>"

        "<div class='pane' id='pane-settings'>"
        "<div class='card'><h3>Settings</h3>"
        "<div class='row'><input id='ssid' placeholder='SSID'><input id='pass' placeholder='Password'><input id='host' placeholder='Hostname'></div>"
        "<button onclick='saveWifi()'>Save Wi-Fi</button>"
        "<button onclick='scanWifi()'>Scan</button>"
        "<div id='wifi_list' class='list'></div>"
        "<div class='muted'>If AP is up: password 12345678.</div>"
        "</div>"
        "<div class='card'><h3>MQTT</h3>"
        "<div class='row'><input id='mqtt_id' placeholder='Broker ID'><input id='mqtt_port' placeholder='Port' style='max-width:140px'><input id='mqtt_keep' placeholder='Keepalive s' style='max-width:160px'></div>"
        "<button onclick='saveMqtt()'>Save</button>"
        "</div>"
"<div class='card'><h3>Publish MQTT</h3>"
"<div class='row'><input id='pub_topic' placeholder='topic'><input id='pub_payload' placeholder='payload'></div>"
"<button onclick='publishMsg()'>Send</button>"
"</div>"
"</div>"
"<div class='pane' id='pane-devices'>"
"<div class='card'><h3>Devices & Automation</h3><div id='device_wizard_root'></div></div>"
"<div class='card wizard-manual-card'>"
"<h4>Manual trigger</h4>"
"<div class='row'><select id='device_run_select'></select><select id='scenario_run_select'></select><button id='device_run_btn'>Run</button></div>"
"<div id='device_run_status' class='muted small'>Select device & scenario</div>"
"</div>"
"<script>"
        "const MAX_PARALLEL_REQUESTS=2;"
        "const __fetchQueue=[];"
        "let __fetchActive=0;"
        "const __origFetch=window.fetch.bind(window);"
        "function __runFetchQueue(){if(__fetchActive>=MAX_PARALLEL_REQUESTS)return;const job=__fetchQueue.shift();if(!job)return;__fetchActive++;__origFetch(...job.args).then(job.resolve,job.reject).finally(()=>{__fetchActive--;__runFetchQueue();});}"
        "window.fetch=(...args)=>new Promise((resolve,reject)=>{__fetchQueue.push({args,resolve,reject});__runFetchQueue();});"
        "const tabs=document.querySelectorAll('.tab');const panes=document.querySelectorAll('.pane');"
"const tabIconDefaults=['status','audio','pictures','laser','robot','devices','settings','network','power'];"
"tabs.forEach((tab,idx)=>{if(!tab.dataset.icon){tab.dataset.icon=tabIconDefaults[idx%tabIconDefaults.length];}});"
"const loadedTabs={status:true,audio:false,pictures:false,laser:false,robot:false,devices:false};"
        "const ROBOT_PRESET_COUNT=8;let robotPresets=new Array(ROBOT_PRESET_COUNT).fill('');"
        "tabs.forEach(t=>t.onclick=()=>{tabs.forEach(x=>x.classList.remove('active'));panes.forEach(p=>p.classList.remove('active'));t.classList.add('active');document.getElementById('pane-'+t.dataset.tab).classList.add('active');ensureTabLoaded(t.dataset.tab);});"
"function ensureTabLoaded(tab){switch(tab){case 'audio':if(!loadedTabs.audio){loadFiles().then(()=>{loadedTabs.audio=true;}).catch(()=>{});}break;case 'pictures':if(!loadedTabs.pictures){loadFiles().then(()=>loadPictures()).then(()=>{loadedTabs.pictures=true;}).catch(()=>{});}break;case 'laser':if(!loadedTabs.laser){loadFiles().then(()=>loadLaser()).then(()=>{loadedTabs.laser=true;}).catch(()=>{});}break;case 'robot':if(!loadedTabs.robot){Promise.all([loadRobot(),loadRobotPresets()]).finally(()=>{loadedTabs.robot=true;});}break;case 'devices':loadedTabs.devices=true;break;default:break;}}"
        "function ping(){fetch('/api/ping').then(r=>r.text()).then(alert);} "
        "let apPopupShown=false;"
        "function updateBanner(j){const b=document.getElementById('banner');const badge=document.getElementById('status_badge');const ap=j.wifi.ap;const ip=j.wifi.sta_ip;badge.textContent=ap?'AP+STA':'STA';badge.style.background=ap?'#f97316':'#1f2430';if(ap){b.textContent='Setup mode: AP+STA, will disable AP after connect.';}else{b.textContent='Connected to '+j.wifi.ssid+' IP '+(ip||'none');}}"
        "function setTxt(id,v){const el=document.getElementById(id);if(el){el.textContent=v;}}"
        "function renderDots(id,count,max){const el=document.getElementById(id);if(!el)return;el.innerHTML='';for(let i=0;i<max;i++){const dot=document.createElement('span');dot.style.background=i<count?'#22c55e':'#1f2937';el.appendChild(dot);}}"
        "function humanMb(bytes){if(!bytes||bytes<=0)return'-';return (bytes/1024/1024).toFixed(1)+' MB';}"
        "function humanGb(bytes){if(!bytes||bytes<=0)return'0 GB';return (bytes/(1024*1024*1024)).toFixed(2)+' GB';}"
        "function renderStatus(j){setTxt('status_raw',JSON.stringify(j,null,2));setTxt('status_ssid',j.wifi.ssid||'n/a');setTxt('status_ip',j.wifi.sta_ip||'none');const sd=j.sd||{};if(sd.ok){setTxt('status_sd_size',`${humanGb(sd.total)} / free ${humanGb(sd.free)}`);}else{setTxt('status_sd_size','No card');}setTxt('status_clients',j.clients?j.clients.total:0);renderDots('clients_pictures',j.clients?j.clients.pictures:0,5);renderDots('clients_laser',j.clients?j.clients.laser:0,2);renderDots('clients_robot',j.clients?j.clients.robot:0,1);const picDots=document.getElementById('cluster_pictures');const laserDots=document.getElementById('cluster_laser');const robotDots=document.getElementById('cluster_robot');if(picDots){picDots.innerHTML='';renderDots('cluster_pictures',j.clients?j.clients.pictures:0,5);}if(laserDots){laserDots.innerHTML='';renderDots('cluster_laser',j.clients?j.clients.laser:0,2);}if(robotDots){robotDots.innerHTML='';renderDots('cluster_robot',j.clients?j.clients.robot:0,1);}}"
        "let rawShown=false;"
        "function toggleRaw(){rawShown=!rawShown;const pre=document.getElementById('status_raw');const btn=document.getElementById('status_raw_btn');if(pre){pre.style.display=rawShown?'block':'none';}if(btn){btn.textContent=rawShown?'Hide raw':'Show raw';}}"
"function loadStatus(){setTxt('status_state','Loading...');return fetch('/api/status').then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(j=>{renderStatus(j);setTxt('status_state','Updated');document.getElementById('ssid').value=j.wifi.ssid;document.getElementById('host').value=j.wifi.host;document.getElementById('mqtt_id').value=j.mqtt.id;document.getElementById('mqtt_port').value=j.mqtt.port;document.getElementById('mqtt_keep').value=j.mqtt.keepalive;updateAudioFromStatus(j.audio||{});updateBanner(j);if(j.wifi.sta_ip && j.wifi.sta_ip.length>0 && j.wifi.ap && !apPopupShown){apPopupShown=true;alert('Connected. IP: '+j.wifi.sta_ip+'\\nDisabling AP.');fetch('/api/ap/stop');}}).catch(err=>{setTxt('status_state','Failed to load');setTxt('status_raw',err.message);});}"
        "function saveWifi(){const s=ssid.value,p=pass.value,h=host.value;fetch(`/api/config/wifi?ssid=${encodeURIComponent(s)}&password=${encodeURIComponent(p)}&host=${encodeURIComponent(h)}`).then(r=>r.text()).then(alert);}"
        "function scanWifi(){fetch('/api/wifi/scan').then(r=>r.json()).then(list=>{const c=document.getElementById('wifi_list');c.innerHTML='';list.forEach(name=>{const d=document.createElement('div');d.className='pill';d.textContent=name;d.onclick=()=>{ssid.value=name;};c.appendChild(d);});});}"
        "function saveMqtt(){const id=mqtt_id.value,port=mqtt_port.value,keep=mqtt_keep.value;fetch(`/api/config/mqtt?id=${encodeURIComponent(id)}&port=${port}&keepalive=${keep}`).then(r=>r.text()).then(alert);}"
        "const PROGRESS_MAX=10000;"
        "const SEEK_DEBOUNCE_MS=150;"
        "const SEEK_ACK_THRESHOLD=50;"
        "const SEEK_MAX_HOLD_MS=2000;"
        "let audioPlaying=false;"
        "let audioPaused=false;"
        "let currentPlayingPath='';"
        "let lastPlayedPath='';"
        "let pendingTrackPath='';"
        "let repeatOne=false;"
        "let repeatInFlight=false;"
        "let progressScrubbing=false;"
        "let seekTimer=null;"
        "let pendingSeekValue=null;"
        "let seekPending=false;"
        "let seekReleaseTimer=null;"
        "let seekAwaitValue=null;"
        "function play(path){const p=path||audio_path.value; if(!p){alert('Select a track');return;}"
        " setFileStatus('Playing...',false);"
        " resetProgressUI(true);"
        " pendingTrackPath=p;"
        " lastPlayedPath=p;"
        " repeatInFlight=false;"
        " const start=()=>fetch(`/api/audio/play?path=${encodeURIComponent(p)}&volume=${audio_vol.value}`).then(r=>r.text()).then(()=>{audioPlaying=true;audioPaused=false;currentPlayingPath=p;setFileStatus('Playing',false);markPlayingCard();}).catch(()=>setFileStatus('Play failed',true));"
        " if(currentPlayingPath){fetch('/api/audio/stop').catch(()=>{}).finally(()=>{start();});}else{start();}"
        "}"
        "function pauseAudio(){fetch('/api/audio/pause').then(()=>{audioPaused=true;setFileStatus('Paused',false);updatePauseBtn();}).catch(()=>setFileStatus('Pause failed',true));}"
        "function resumeAudio(){fetch('/api/audio/resume').then(()=>{audioPaused=false;setFileStatus('Playing',false);updatePauseBtn();}).catch(()=>setFileStatus('Resume failed',true));}"
        "function togglePause(){if(audioPaused){resumeAudio();}else{pauseAudio();}}"
        "function updatePauseBtn(){const btn=document.getElementById('audio_pause_btn');if(!btn)return;btn.title=audioPaused?'Resume':'Pause';if(audioPaused){btn.classList.add('icon-play');btn.classList.remove('icon-pause');}else{btn.classList.add('icon-pause');btn.classList.remove('icon-play');}}"
        "function stopPlay(){fetch('/api/audio/stop').then(()=>{audioPlaying=false;audioPaused=false;currentPlayingPath='';lastPlayedPath='';pendingTrackPath='';repeatInFlight=false;markPlayingCard();setFileStatus('Stopped',false);resetProgressUI(true);updatePauseBtn();}).catch(()=>setFileStatus('Stop failed',true));}"
        "function setVolume(v){volInput(v);}"
        "function publishMsg(){fetch(`/api/publish?topic=${encodeURIComponent(pub_topic.value)}&payload=${encodeURIComponent(pub_payload.value)}`).then(r=>r.text());}"
        "let filesData=[];"
        "let filesDataPath='/sdcard';"
        "let currentDir='/sdcard';"
        "let rootDirs=[];"
        "let picturesConfig=null;"
        "function ensureTrackOption(sel,value){if(!sel||!value)return;let exists=false;Array.from(sel.options||[]).forEach(o=>{if(o.value===value)exists=true;});if(!exists){const opt=document.createElement('option');opt.value=value;opt.textContent=value.split('/').pop();sel.appendChild(opt);}sel.value=value;}"
        "function applyPicSelections(cfg){if(!cfg)return;ensureTrackOption(document.getElementById('track_ok_select'),cfg.ok);ensureTrackOption(document.getElementById('track_fail_select'),cfg.fail);}"
        "const playPalette=['#d8b4fe','#c084fc','#5eead4','#22d3ee','#fdba74','#fb923c','#fcd34d','#fde68a'];"
        "function colorForIndex(idx){return playPalette[idx%playPalette.length];}"
        "function adjustColor(hex,amount){if(!hex)return'#000000';let c=hex.replace('#','');if(c.length===3){c=c.split('').map(ch=>ch+ch).join('');}const num=parseInt(c,16);if(isNaN(num))return hex;const clamp=v=>Math.min(255,Math.max(0,v));const r=clamp((num>>16)+amount);const g=clamp(((num>>8)&0xFF)+amount);const b=clamp((num&0xFF)+amount);const toHex=v=>v.toString(16).padStart(2,'0');return `#${toHex(r)}${toHex(g)}${toHex(b)}`;}"
        "function stylePad(el,idx){const c=colorForIndex(idx);const lighter=adjustColor(c,70);const darker=adjustColor(c,-30);el.style.backgroundColor=c;el.style.backgroundImage=`linear-gradient(135deg, ${lighter}, ${darker})`;el.style.boxShadow='0 6px 14px rgba(0,0,0,0.35)';}"
        "function tintTabs(){tabs.forEach((tab,idx)=>{const c=colorForIndex(idx);const lighter=adjustColor(c,70);const darker=adjustColor(c,-30);tab.style.setProperty('--tab-color',c);tab.style.backgroundColor=c;tab.style.backgroundImage=`linear-gradient(135deg, ${lighter}, ${darker})`;tab.style.borderColor=darker;});}"
        "tintTabs();"
        "function truncateName(name,max=16){if(!name)return'';return name.length>max?name.slice(0,max-3)+'...':name;}"
        "let volTimer=null;let volPending=null;"
        "function sendVolumeNow(v){fetch(`/api/audio/volume?val=${v}`).catch(()=>{});}"
        "function volInput(v){audio_vol_val.textContent=v;volPending=v;if(volTimer){return;}volTimer=setTimeout(()=>{if(volPending!==null){sendVolumeNow(volPending);}volPending=null;volTimer=null;},150);}"
        "function setFileStatus(msg,isError){const els=[document.getElementById('audio_status')];els.forEach(el=>{if(el){el.textContent=msg||'';el.style.color=isError?'#f87171':'#8b92a3';}});}"
        "function humanSize(bytes){if(!bytes||bytes<=0)return'-';const kb=1024,mb=kb*1024;if(bytes>=mb)return (bytes/mb).toFixed(1)+' MB';return Math.round(bytes/kb)+' KB';}"
        "function formatTime(ms){if(!ms||ms<=0)return'0:00';const totalSeconds=Math.floor(ms/1000);const minutes=Math.floor(totalSeconds/60);const seconds=(totalSeconds%60).toString().padStart(2,'0');return `${minutes}:${seconds}`;}"
        "let currentBitrateKbps=0;"
        "let lastProgressLabel='';"
        "function markPlayingCard(){const cards=document.querySelectorAll('.track-card');cards.forEach(c=>{const p=c.dataset.path||'';if(currentPlayingPath&&p===currentPlayingPath){c.classList.add('playing');}else{c.classList.remove('playing');}});}"
        "function resetProgressUI(disable){if(disable===undefined)disable=true;if(seekTimer){clearTimeout(seekTimer);seekTimer=null;}if(seekReleaseTimer){clearTimeout(seekReleaseTimer);seekReleaseTimer=null;}pendingSeekValue=null;seekAwaitValue=null;seekPending=false;progressScrubbing=false;const prog=document.getElementById('audio_prog');if(prog){prog.value=0;if(disable){prog.disabled=true;}delete prog.dataset.dur_ms;}const progTxt=document.getElementById('audio_prog_txt');if(progTxt){lastProgressLabel='0:00 / ?';progTxt.textContent=lastProgressLabel;}}"
        "function clampProgressValue(value){const num=Number(value);if(isNaN(num))return 0;return Math.min(Math.max(Math.round(num),0),PROGRESS_MAX);}"
        "function progressFraction(value){return clampProgressValue(value)/PROGRESS_MAX;}"
        "function scheduleSeek(value){pendingSeekValue=clampProgressValue(value);if(seekTimer){return;}seekTimer=setTimeout(()=>{seekTimer=null;if(pendingSeekValue===null)return;seekAudio(pendingSeekValue);pendingSeekValue=null;},SEEK_DEBOUNCE_MS);}"
        "function holdSeekPosition(value){seekPending=true;seekAwaitValue=clampProgressValue(value);if(seekReleaseTimer){clearTimeout(seekReleaseTimer);}seekReleaseTimer=setTimeout(()=>{seekPending=false;seekReleaseTimer=null;seekAwaitValue=null;},SEEK_MAX_HOLD_MS);}"
        "function releaseSeekHold(){if(seekReleaseTimer){clearTimeout(seekReleaseTimer);seekReleaseTimer=null;}seekPending=false;seekAwaitValue=null;}"
        "function failSeek(msg){releaseSeekHold();if(msg){setFileStatus(msg,true);}}"
        "function startScrub(){progressScrubbing=true;}"
        "function finishScrub(){progressScrubbing=false;}"
        "function commitScrub(value){finishScrub();holdSeekPosition(value);scheduleSeek(value);}"
        "function seekAudio(value){if(!(audioPlaying||audioPaused)){failSeek();return;}const prog=document.getElementById('audio_prog');if(!prog||!prog.dataset.dur_ms){failSeek('Cannot seek right now');return;}const dur=parseInt(prog.dataset.dur_ms,10);if(!dur||dur<=0){failSeek('Cannot seek: unknown duration');return;}const frac=progressFraction(value);const target=Math.floor(dur*frac);fetch(`/api/audio/seek?pos=${target}`).then(r=>{if(!r.ok)throw new Error('seek');return r.text();}).catch(()=>failSeek('Seek failed'));}"
        "function scrubPreview(value){progressScrubbing=true;if(!(audioPlaying||audioPaused))return;const progTxt=document.getElementById('audio_prog_txt');const prog=document.getElementById('audio_prog');if(!prog||!progTxt||!prog.dataset.dur_ms)return;const dur=parseInt(prog.dataset.dur_ms,10);if(!dur||dur<=0)return;const frac=progressFraction(value);const preview=formatTime(Math.floor(dur*frac));const full=formatTime(dur);progTxt.textContent=`${preview} / ${full}`;}"
        "function updateAudioFromStatus(a){if(!a)a={};const statusPath=a.path||'';const progressLocked=pendingTrackPath&&a.playing&&statusPath!==pendingTrackPath;const vol=document.getElementById('audio_vol');const volVal=document.getElementById('audio_vol_val');if(vol){vol.value=a.volume||a.audio_volume||vol.value;if(volVal){volVal.textContent=vol.value;}}const prog=document.getElementById('audio_prog');const progTxt=document.getElementById('audio_prog_txt');if(prog){if(a.dur_ms){prog.dataset.dur_ms=a.dur_ms;}let sliderVal=0;if(a.progress!==undefined&&a.progress!==null){const raw=a.progress<=1?Math.round(a.progress*PROGRESS_MAX):Math.round(a.progress*100);sliderVal=clampProgressValue(raw);}if(seekPending&&seekAwaitValue!==null){const delta=Math.abs(sliderVal-seekAwaitValue);if(delta<=SEEK_ACK_THRESHOLD){releaseSeekHold();}}if(!progressScrubbing&&!seekPending&&!progressLocked){prog.value=sliderVal;}const sliderEnabled=(a.playing||a.paused)&&!progressLocked;prog.disabled=!sliderEnabled;}if(progTxt&&!progressScrubbing&&!seekPending&&!progressLocked){const posLabel=formatTime(a.pos_ms);const durLabel=a.dur_ms&&a.dur_ms>0?formatTime(a.dur_ms):'?';const combined=`${posLabel} / ${durLabel}`;if(combined!==lastProgressLabel){progTxt.textContent=combined;lastProgressLabel=combined;}}const st=document.getElementById('audio_status');if(st){if(a.playing){st.textContent=`Playing: ${statusPath}${a.paused?' (paused)':''}`;}else if(a.message){st.textContent=`${a.message}${statusPath?' '+statusPath:''}`;}else if(statusPath){st.textContent=`Ready: ${statusPath}`;}else{st.textContent='Idle';}}if(a.playing){if(pendingTrackPath&&statusPath===pendingTrackPath){pendingTrackPath=''; currentPlayingPath=statusPath||currentPlayingPath;}else if(!pendingTrackPath&&statusPath){currentPlayingPath=statusPath;}}else if(!a.paused){pendingTrackPath='';currentPlayingPath='';}audioPlaying=!!a.playing;audioPaused=!!a.paused;if(a.playing&&statusPath){lastPlayedPath=statusPath;}if(a.playing){repeatInFlight=false;}currentBitrateKbps=a.bitrate||0;markPlayingCard();updatePauseBtn();if(repeatOne&&!a.playing&&lastPlayedPath&&!repeatInFlight){repeatInFlight=true;play(lastPlayedPath);}}"
        "function setPathLabel(){const lbl=document.getElementById('path_label');if(lbl){lbl.textContent=currentDir;}}"
        "function enterDir(path){currentDir=path||'/sdcard';setPathLabel();loadFiles();}"
        "function navUp(){if(!currentDir||currentDir==='/sdcard'){return;}const parts=currentDir.split('/');parts.pop();if(parts.length<2){currentDir='/sdcard';}else{currentDir=parts.join('/');}setPathLabel();loadFiles();}"
        "function renderFolders(dirs,currentDirs){const bar=document.getElementById('audio_folders');if(!bar)return;bar.innerHTML='';const seen=new Set();let idx=0;const addChip=(d)=>{if(!d||!d.path)return;const key=d.path;if(seen.has(key))return;seen.add(key);const chip=document.createElement('div');chip.className='folder-chip';chip.style.borderColor=colorForIndex(idx);chip.onclick=()=>enterDir(d.path);if(currentDir===d.path){chip.classList.add('active');}chip.textContent=truncateName(d.name||d.path);chip.title=d.path;bar.appendChild(chip);idx++;};(dirs||[]).forEach(addChip);(currentDirs||[]).forEach(addChip);}"
        "function renderFiles(list){filesData=list||[];const audioBox=document.getElementById('audio_files');if(audioBox){audioBox.innerHTML='';}"
         " if(!list||list.length===0){[audioBox].forEach(c=>{if(!c)return;const empty=document.createElement('div');empty.className='muted small';empty.textContent='No files';c.appendChild(empty);});return;}"
         " const okSel=document.getElementById('track_ok_select');const failSel=document.getElementById('track_fail_select');const lHold=document.getElementById('laser_hold_select');const lRelay=document.getElementById('laser_relay_select');[okSel,failSel,lHold,lRelay].forEach(sel=>{if(sel){sel.innerHTML='<option value=\"\">-- track --</option>';}});"
         " const dirs=[];"
         " let padIdx=0;"
         " list.forEach(f=>{const path=f.path||f;const size=f.size||0;const dur=f.dur||0;"
        "   if(f.dir){dirs.push({path, name:path.split('/').pop()||path});return;}"
        "   if(audioBox){const card=document.createElement('div');card.className='track-card';card.dataset.path=path;stylePad(card,padIdx++);card.onclick=()=>{audio_path.value=path;play(path);};"
        "     const name=document.createElement('div');name.className='track-name';name.textContent=path.split('/').pop();card.appendChild(name);"
        "     audioBox.appendChild(card);}"
        "   [okSel,failSel,lHold,lRelay].forEach(sel=>{if(sel){const opt=document.createElement('option');opt.value=path;opt.textContent=path.split('/').pop();sel.appendChild(opt);}});"
         " });"
        " if(picturesConfig){applyPicSelections(picturesConfig);}"
        " renderFolders(rootDirs.length?rootDirs:dirs, dirs);"
        " markPlayingCard();}"
        "function loadRobot(){return fetch('/api/robot/config').then(r=>{if(!r.ok)throw new Error('robot');return r.json();}).then(cfg=>{const laser=document.getElementById('robot_laser_dir');const sarc=document.getElementById('robot_sarcasm_dir');const broken=document.getElementById('robot_broken_dir');if(laser){laser.value=cfg.laser||'';}if(sarc){sarc.value=cfg.sarcastic||'';}if(broken){broken.value=cfg.broken||'';}const st=document.getElementById('robot_status');if(st){st.textContent='Loaded';}return cfg;}).catch(()=>{});}"
        "function saveRobotCfg(){const laser=document.getElementById('robot_laser_dir').value||'';const sarc=document.getElementById('robot_sarcasm_dir').value||'';const broken=document.getElementById('robot_broken_dir').value||'';const st=document.getElementById('robot_status');const url=`/api/robot/save?laser=${encodeURIComponent(laser)}&sarcastic=${encodeURIComponent(sarc)}&broken=${encodeURIComponent(broken)}`;fetch(url).then(r=>r.text()).then(()=>{if(st){st.textContent='Saved';}}).catch(()=>{if(st){st.textContent='Save failed';}});}"
        "function publishSarcasm(){const dir=document.getElementById('robot_sarcasm_dir').value||'';if(!dir){alert('Select sarcastic folder');return;}fetch(`/api/publish?topic=${encodeURIComponent('robot/mode/sarcastic')}&payload=${encodeURIComponent(dir)}`).then(()=>{const st=document.getElementById('robot_status');if(st){st.textContent='Sent sarcastic';}}).catch(()=>{});}"
        "const MODE_EXIT_DELAY_MS=800;"
        "let sarcasmOn=false;"
        "let brokenOn=false;"
        "let modeLast='';"
        "let modeBusy=false;"
        "function delayMs(ms){return new Promise(resolve=>setTimeout(resolve,ms));}"
        "function refreshModeButtons(){const sarc=document.getElementById('sarcasm_btn');const broken=document.getElementById('broken_btn');[sarc,broken].forEach(btn=>{if(btn){btn.disabled=modeBusy;}});if(sarc){sarc.classList.toggle('active',sarcasmOn);sarc.classList.toggle('mode-last',modeLast==='sarcasm');}if(broken){broken.classList.toggle('active',brokenOn);broken.classList.toggle('mode-last',modeLast==='broken');}}"
        "function setModeLast(name){modeLast=name||'';refreshModeButtons();}"
        "function setSarcasm(on){return fetch(`/api/publish?topic=${encodeURIComponent('robot/mode/sarcastic')}&payload=${encodeURIComponent(on?'on':'off')}`).then(()=>{sarcasmOn=on;if(on){setModeLast('sarcasm');}else if(!brokenOn){setModeLast('');}refreshModeButtons();});}"
        "function setBroken(on){const dir=document.getElementById('robot_broken_dir').value||'';if(on&&!dir){alert('Enter broken folder');return Promise.reject(new Error('missing broken dir'));}const topic=on?'robot/broken/on':'robot/broken/off';const payload=on?dir:'off';return fetch(`/api/publish?topic=${encodeURIComponent(topic)}&payload=${encodeURIComponent(payload)}`).then(()=>{brokenOn=on;if(on){setModeLast('broken');}else if(!sarcasmOn){setModeLast('');}refreshModeButtons();});}"
        "function ensureBrokenOff(){if(!brokenOn)return Promise.resolve();return setBroken(false).then(()=>delayMs(MODE_EXIT_DELAY_MS));}"
        "function ensureSarcasmOff(){if(!sarcasmOn)return Promise.resolve();return setSarcasm(false).then(()=>delayMs(MODE_EXIT_DELAY_MS));}"
        "function toggleSarcasm(){const next=!sarcasmOn;if(modeBusy)return;modeBusy=true;refreshModeButtons();(next?ensureBrokenOff():Promise.resolve()).then(()=>setSarcasm(next)).catch(()=>{}).finally(()=>{modeBusy=false;refreshModeButtons();});}"
        "function toggleBroken(){const next=!brokenOn;if(modeBusy)return;modeBusy=true;refreshModeButtons();(next?ensureSarcasmOff():Promise.resolve()).then(()=>setBroken(next)).catch(()=>{}).finally(()=>{modeBusy=false;refreshModeButtons();});}"
        "function renderRobotPresets(){const grid=document.getElementById('robot_presets');if(!grid)return;grid.innerHTML='';for(let i=0;i<ROBOT_PRESET_COUNT;i++){const slot=document.createElement('div');slot.className='robot-slot';const label=document.createElement('div');label.className='robot-slot-label';label.textContent=`Slot ${i+1}`;slot.appendChild(label);const card=document.createElement('div');card.className='track-card robot-card';stylePad(card,i);card.onclick=()=>playPreset(i);card.title='Play preset';const edit=document.createElement('button');edit.className='robot-edit-btn';edit.textContent='+';edit.title='Edit preset';edit.onclick=ev=>{ev.stopPropagation();editPreset(i);};card.appendChild(edit);const name=document.createElement('div');name.className='track-name';name.textContent=robotPresets[i]||'Empty';card.appendChild(name);slot.appendChild(card);grid.appendChild(slot);}}"
        "function loadRobotPresets(){return fetch('/api/robot/presets').then(r=>{if(!r.ok)throw new Error('preset');return r.json();}).then(arr=>{robotPresets=new Array(ROBOT_PRESET_COUNT).fill('');(arr||[]).forEach((n,idx)=>{if(idx<ROBOT_PRESET_COUNT){robotPresets[idx]=n||'';}});renderRobotPresets();}).catch(()=>{renderRobotPresets();});}"
        "function editPreset(idx){const current=robotPresets[idx]||'';const name=prompt('Track name (without .mp3)', current);if(name===null)return;const clean=(name||'').trim();fetch(`/api/robot/preset_set?idx=${idx}&name=${encodeURIComponent(clean)}`).then(()=>{robotPresets[idx]=clean;renderRobotPresets();}).catch(()=>{});}"
        "function playPreset(idx){const name=robotPresets[idx];if(!name){alert('Slot is empty');return;}fetch(`/api/robot/preset_play?idx=${idx}`).catch(()=>{});}"
        "function loadRootFolders(){return fetch('/api/files?path=/sdcard').then(r=>{if(!r.ok)throw new Error('sd');return r.json();}).then(list=>{rootDirs=(list||[]).filter(x=>x.dir).map(x=>({path:x.path,name:x.path.split('/').pop()||x.path}));}).catch(()=>{rootDirs=[];});}"
        "function loadFiles(force=false){if(!force&&filesData&&filesData.length&&filesDataPath===currentDir){renderFiles(filesData);setFileStatus(filesData.length?'Choose a file to play':'No audio files found',false);return Promise.resolve(filesData);}setFileStatus('Loading files...');setPathLabel();const url=`/api/files?path=${encodeURIComponent(currentDir)}`;const ensureRoot=currentDir==='/sdcard'?loadRootFolders():Promise.resolve();return ensureRoot.then(()=>fetch(url)).then(r=>{if(!r.ok)throw new Error('sd');return r.json();}).then(list=>{filesData=list;filesDataPath=currentDir;renderFiles(list);setFileStatus(list.length?'Choose a file to play':'No audio files found',false);return list;}).catch(err=>{filesData=null;renderFiles([]);setFileStatus('SD error',true);throw err;});}"
        "function renderPicGrid(cfg){const grid=document.getElementById('pic_grid');if(!grid)return;grid.innerHTML='';const status=document.getElementById('pic_status');if(status){status.textContent='';}"
        "cfg.devices.forEach(d=>{const card=document.createElement('div');card.className='pic-card';const title=document.createElement('div');title.innerHTML=`<strong>ESP ${d.idx}</strong>`;card.appendChild(title);const last=document.createElement('div');last.className='pic-last';last.dataset.idx=d.idx;last.textContent='Last: '+(d.last||'-');card.appendChild(last);"
        "const wrap=document.createElement('div');wrap.className='pic-uids';for(let i=0;i<10;i++){const inp=document.createElement('input');inp.placeholder='UID';inp.value=d.uids[i]||'';inp.dataset.idx=d.idx;inp.dataset.pos=i;wrap.appendChild(inp);}card.appendChild(wrap);"
        "const actions=document.createElement('div');actions.className='track-actions';const save=document.createElement('button');save.textContent='Save';save.onclick=()=>saveDevice(d.idx);const clear=document.createElement('button');clear.textContent='Clear';clear.onclick=()=>{wrap.querySelectorAll('input').forEach(inp=>inp.value='');saveDevice(d.idx);};actions.appendChild(save);actions.appendChild(clear);card.appendChild(actions);grid.appendChild(card);});"
        "picturesConfig=cfg;applyPicSelections(cfg);}"
        "function collectUids(idx){const inputs=document.querySelectorAll(`.pic-card input[data-idx='${idx}']`);const uids=[];inputs.forEach(inp=>{if(inp.value.trim().length>0)uids.push(inp.value.trim());});return uids.join(',');}"
        "function saveDevice(idx){const u=collectUids(idx);fetch(`/api/pictures/device/save?idx=${idx}&uids=${encodeURIComponent(u)}`).then(r=>r.text()).then(()=>{picturesCache=null;document.getElementById('pic_status').textContent='Saved device '+idx;loadPictures(true);});}"
        "function saveTracks(){const ok=document.getElementById('track_ok_select').value;const fail=document.getElementById('track_fail_select').value;fetch(`/api/pictures/tracks/save?ok=${encodeURIComponent(ok)}&fail=${encodeURIComponent(fail)}`).then(()=>{picturesCache=null;document.getElementById('pic_status').textContent='Tracks saved';setTimeout(()=>loadPictures(true),200);});}"
        "function toggleAddMode(on){fetch(`/api/pictures/addmode?mode=${on?'on':'off'}`).then(()=>{document.getElementById('pic_status').textContent=on?'Add mode ON':'Add mode OFF';});}"
        "function refreshPicLast(){fetch('/api/pictures/status').then(r=>r.json()).then(status=>{(status.devices||[]).forEach(d=>{const last=document.querySelector(`.pic-last[data-idx='${d.idx}']`);if(last){last.textContent='Last: '+(d.last||'-');last.classList.toggle('active',!!d.active);}});}).catch(()=>{});}"
        "function forceCheck(){fetch('/api/pictures/scan').then(()=>new Promise(r=>setTimeout(r,700))).then(()=>fetch('/api/pictures/check')).then(r=>r.json()).then(res=>{document.getElementById('pic_status').textContent=res.ok?'OK':'FAIL';refreshPicLast();});}"
        "let laserEnabled=true;"
        "function updateLaserToggle(){const btn=document.getElementById('laser_toggle_btn');const st=document.getElementById('laser_toggle_status');if(btn){btn.textContent=laserEnabled?'Disable':'Enable';}if(st){st.textContent=laserEnabled?'Laser processing ON':'Laser processing OFF';st.style.color=laserEnabled?'#22c55e':'#f87171';}}"
        "function toggleLaser(){const next=!laserEnabled;fetch(`/api/laser/enable?state=${next?'on':'off'}`).then(r=>r.json()).then(j=>{laserEnabled=!!j.enabled;updateLaserToggle();}).catch(()=>{});}"
        "function saveLaser(){const hold=document.getElementById('laser_hold_select').value;const relay=document.getElementById('laser_relay_select').value;const sec=document.getElementById('laser_seconds').value||20;const mode=document.getElementById('laser_mode').value;const stat=document.getElementById('laser_status');fetch(`/api/laser/save?hold=${encodeURIComponent(hold)}&relay=${encodeURIComponent(relay)}&seconds=${encodeURIComponent(sec)}&mode=${encodeURIComponent(mode)}&enabled=${laserEnabled?'on':'off'}`).then(r=>r.text()).then(()=>{if(stat){stat.textContent='Saved';}});}"
 
        "let picturesCache=null;"
        "function loadPictures(force=false){if(!force&&picturesCache){renderPicGrid(picturesCache);refreshPicLast();return Promise.resolve(picturesCache);}return fetch('/api/pictures/config').then(r=>{if(!r.ok)throw new Error('pictures');return r.json();}).then(cfg=>{picturesCache=cfg;renderPicGrid(cfg);refreshPicLast();return cfg;}).catch(err=>{const s=document.getElementById('pic_status');if(s){s.textContent='Load failed';}throw err;});}"
        "function loadLaser(){return fetch('/api/laser/config').then(r=>{if(!r.ok)throw new Error('laser');return r.json();}).then(cfg=>{const hold=document.getElementById('laser_hold_select');const relay=document.getElementById('laser_relay_select');const sec=document.getElementById('laser_seconds');const mode=document.getElementById('laser_mode');const stat=document.getElementById('laser_status');if(hold&&cfg.hold){let ex=false;Array.from(hold.options||[]).forEach(o=>{if(o.value===cfg.hold)ex=true;});if(!ex){const opt=document.createElement('option');opt.value=cfg.hold;opt.textContent=cfg.hold.split('/').pop();hold.appendChild(opt);}hold.value=cfg.hold;}if(relay&&cfg.relay){let ex=false;Array.from(relay.options||[]).forEach(o=>{if(o.value===cfg.relay)ex=true;});if(!ex){const opt=document.createElement('option');opt.value=cfg.relay;opt.textContent=cfg.relay.split('/').pop();relay.appendChild(opt);}relay.value=cfg.relay;}if(sec&&cfg.seconds){sec.value=cfg.seconds;}if(mode&&cfg.mode){mode.value=cfg.mode;}laserEnabled=!!cfg.enabled;updateLaserToggle();if(stat){stat.textContent='Loaded';}return cfg;});}"
        "function assignFile(){const f=document.getElementById('audio_topic').value||'';const t=audio_topic.value;if(!f){alert('file?');return;}if(!t){alert('topic');return;}setFileStatus('Rules disabled in this build',true);}"
        "let statusInterval=null;"
        "function fetchAudioStatus(){return fetch('/api/status').then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(j=>{if(j.audio){updateAudioFromStatus(j.audio);}}).catch(()=>{});}"
        "function toggleRepeat(){repeatOne=!repeatOne;const btn=document.getElementById('audio_repeat_btn');if(btn){if(repeatOne){btn.classList.add('active');}else{btn.classList.remove('active');}}}"
        "refreshModeButtons();"
        "loadStatus().then(()=>{if(statusInterval)clearInterval(statusInterval);statusInterval=setInterval(()=>{const activePane=document.querySelector('.pane.active');if(!activePane)return;const activeId=activePane.id;if(activeId==='pane-status'||activeId==='pane-audio'){fetchAudioStatus();}},3000);});"
        "</script><script src='/ui/devices.js?v=3'></script>"
        "</div>"
        "</body></html>";

const char *web_ui_get_index_html(void)
{
    return s_web_ui_index;
}
