#pragma once

#define DEVICE_MANAGER_MAX_DEVICES               12
#define DEVICE_MANAGER_MAX_TOPICS_PER_DEVICE     6
#define DEVICE_MANAGER_MAX_SCENARIOS_PER_DEVICE  8
#define DEVICE_MANAGER_MAX_STEPS_PER_SCENARIO   16
#define DEVICE_MANAGER_MAX_FLAG_RULES            4
#define DEVICE_MANAGER_MAX_PROFILES             25

#define DEVICE_MANAGER_ID_MAX_LEN               32
#define DEVICE_MANAGER_NAME_MAX_LEN             48
#define DEVICE_MANAGER_TOPIC_MAX_LEN            96
#define DEVICE_MANAGER_PAYLOAD_MAX_LEN         160
#define DEVICE_MANAGER_FLAG_NAME_MAX_LEN        32
#define DEVICE_MANAGER_TRACK_NAME_MAX_LEN       64
#define DEVICE_MANAGER_BUTTON_LABEL_MAX_LEN     DEVICE_MANAGER_NAME_MAX_LEN
